### ISSUE TITLE
Error Mariadb

### ISSUE THREAD

**Issue by mdosch** [movim/movim#1033]
Movim: v0.19

According to [the documentation](https://github.com/movim/movim/wiki/Install-Movim#get-started) MariaDB 10.2 or higher is supported, but with MariaDB 10.5.12 I get the following error:

```
movim.ERROR: Illuminate\Database\QueryException: SQLSTATE[42000]: Syntax error or access violation: 1235 This version of MariaDB doesn't yet support 'LIMIT & IN/ALL/ANY/SOME subquery' (SQL: select * from `posts` where `parent_id` in (select `id` from `posts` where `aid` = martin@mdosch.de order by `published` desc limit 15) order by `published` desc limit 30) in /var/www/social.mdosch.de/movim/vendor/illuminate/database/Connection.php (line 703) Trace 
#0 /var/www/social.mdosch.de/movim/vendor/illuminate/database/Connection.php(663): Illuminate\Database\Connection->runQueryCallback('select * from `...', Array, Object(Closure)) 
#1 /var/www/social.mdosch.de/movim/vendor/illuminate/database/Connection.php(367): Illuminate\Database\Connection->run('select * from `...', Array, Object(Closure)) 
#2 /var/www/social.mdosch.de/movim/vendor/illuminate/database/Query/Builder.php(2352): Illuminate\Database\Connection->select('select * from `...', Array, true) 
#3 /var/www/social.mdosch.de/movim/vendor/illuminate/database/Query/Builder.php(2340): Illuminate\Database\Query\Builder->runSelect() 
#4 /var/www/social.mdosch.de/movim/vendor/illuminate/database/Query/Builder.php(2874): Illuminate\Database\Query\Builder->Illuminate\Database\Query\{closure}() 
#5 /var/www/social.mdosch.de/movim/vendor/illuminate/database/Query/Builder.php(2341): Illuminate\Database\Query\Builder->onceWithColumns(Array, Object(Closure)) 
#6 /var/www/social.mdosch.de/movim/vendor/illuminate/database/Eloquent/Builder.php(615): Illuminate\Database\Query\Builder->get(Array) 
#7 /var/www/social.mdosch.de/movim/vendor/illuminate/database/Eloquent/Builder.php(599): Illuminate\Database\Eloquent\Builder->getModels(Array) 
#8 /var/www/social.mdosch.de/movim/app/widgets/Notifications/Notifications.php(163): Illuminate\Database\Eloquent\Builder->get() 
#9 /var/www/social.mdosch.de/movim/app/widgets/Notifications/Notifications.php(53): Notifications->prepareNotifications() 
#10 /var/www/social.mdosch.de/movim/src/Movim/Widget/Wrapper.php(152): Notifications->ajaxRequest() 
#11 /var/www/social.mdosch.de/movim/src/Movim/RPC.php(45): Movim\Widget\Wrapper->runWidget('Notifications', 'ajaxRequest', Array) 
#12 /var/www/social.mdosch.de/movim/linker.php(189): Movim\RPC->handleJSON(Object(stdClass)) 
#13 /var/www/social.mdosch.de/movim/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(123): {closure}(Object(stdClass), Object(Ratchet\Client\WebSocket)) 
#14 /var/www/social.mdosch.de/movim/vendor/ratchet/pawl/src/WebSocket.php(72): Ratchet\Client\WebSocket->emit('message', Array) 
#15 /var/www/social.mdosch.de/movim/vendor/ratchet/rfc6455/src/Messaging/MessageBuffer.php(248): Ratchet\Client\WebSocket->Ratchet\Client\{closure}(Object(Ratchet\RFC6455\Messaging\Message), Object(Ratchet\RFC6455\Messaging\MessageBuffer)) 
#16 /var/www/social.mdosch.de/movim/vendor/ratchet/rfc6455/src/Messaging/MessageBuffer.php(194): Ratchet\RFC6455\Messaging\MessageBuffer->processData('\x81>{"func":"mess...') 
#17 /var/www/social.mdosch.de/movim/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(123): Ratchet\RFC6455\Messaging\MessageBuffer->onData('\x81>{"func":"mess...') 
#18 /var/www/social.mdosch.de/movim/vendor/react/stream/src/Util.php(71): Evenement\EventEmitter->emit('data', Array) 
#19 /var/www/social.mdosch.de/movim/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(123): React\Stream\Util::React\Stream\{closure}('\x81>{"func":"mess...') 
#20 /var/www/social.mdosch.de/movim/vendor/react/stream/src/DuplexResourceStream.php(196): Evenement\EventEmitter->emit('data', Array) 
#21 /var/www/social.mdosch.de/movim/vendor/react/event-loop/src/StreamSelectLoop.php(245): React\Stream\DuplexResourceStream->handleData(Resource id 
#247) 
#22 /var/www/social.mdosch.de/movim/vendor/react/event-loop/src/StreamSelectLoop.php(212): React\EventLoop\StreamSelectLoop->waitForStreamActivity(1000000) 
#23 /var/www/social.mdosch.de/movim/linker.php(329): React\EventLoop\StreamSelectLoop->run() 
#24 {main} [] []
```
```

**Comment by edhelas** [comment]
MySQL/MariaDB :roll_eyes:

**Comment by edhelas** [comment]
Fixed on master in March, sorry i'm not releasing often but it was fixed a long time ago.
See https://github.com/movim/movim/commit/c3aebf31a688f1af58b658d8f15a97ec1f27926a#diff-5d781b7ae57813069abf6e6e3d02fbdbc4884b6f48766005a77c5e5b210bdd38
