### ISSUE TITLE
Crash when receiving empty messages

### ISSUE THREAD

**Issue by edhelas** [movim/movim#1101]
Stack trace

```
Error: Call to a member function isEmpty() on null in /var/www/movim/app/widgets/Chat/Chat.php (line 132) Trace 
#0 /var/www/movim/src/Movim/Widget/Wrapper.php(190): Chat->onMessage() 
#1 /var/www/movim/lib/moxl/src/Xec/Payload/Payload.php(78): Movim\Widget\Wrapper->iterate() 
#2 /var/www/movim/lib/moxl/src/Xec/Payload/Payload.php(67): Moxl\Xec\Payload\Payload->event() 
#3 /var/www/movim/lib/moxl/src/Xec/Payload/Carbons.php(36): Moxl\Xec\Payload\Payload->deliver() 
#4 /var/www/movim/lib/moxl/src/Xec/Handler.php(197): Moxl\Xec\Payload\Carbons->handle() 
#5 /var/www/movim/lib/moxl/src/Xec/Handler.php(113): Moxl\Xec\Handler::searchPayload() 
#6 /var/www/movim/lib/moxl/src/Xec/Handler.php(84): Moxl\Xec\Handler::handleNode() 
#7 /var/www/movim/linker.php(43): Moxl\Xec\Handler::handle() 
#8 [internal function]: {closure}() 
#9 /var/www/movim/lib/moxl/src/Parser.php(104): call_user_func_array() 
#10 [internal function]: Moxl\Parser->end() 
#11 /var/www/movim/lib/moxl/src/Parser.php(49): xml_parse() 
#12 /var/www/movim/linker.php(300): Moxl\Parser->parse() 
#13 /var/www/movim/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(123): {closure}() 
#14 /var/www/movim/vendor/react/stream/src/Util.php(71): Evenement\EventEmitter->emit() 
#15 /var/www/movim/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(123): React\Stream\Util::React\Stream\{closure}() 
#16 /var/www/movim/vendor/react/stream/src/DuplexResourceStream.php(196): Evenement\EventEmitter->emit() 
#17 /var/www/movim/vendor/react/event-loop/src/StreamSelectLoop.php(246): React\Stream\DuplexResourceStream->handleData() 
#18 /var/www/movim/vendor/react/event-loop/src/StreamSelectLoop.php(213): React\EventLoop\StreamSelectLoop->waitForStreamActivity() 
#19 /var/www/movim/linker.php(330): React\EventLoop\StreamSelectLoop->run() 
#20 {main} [] []
```

> seulement quand tu réagis à un de tes propres messages et que la réaction est "interdite", ie, que movim reçoit immédiatement un carbon avec "reactions vides"

**Comment by truenicoco** [comment]
Full log below, but the interesting part is this (last stanza): `<reactions xmlns='urn:xmpp:reactions:0' id='2402287616' />`

Problem is, `2402287616` is not a valid message ID, movim probably never heard of it.

```xml
<message xmlns="jabber:client" to="5308963142@telegram.localhost" type="chat" id="96f6eaa6-6fb1-4bbd-8cfc-1ffd1c2f6296">
    <reactions xmlns="urn:xmpp:reactions:0" id="c65e1538-8dd6-48ad-9e5c-6650e459c3e1">
        <reaction>🍄</reaction>
    </reactions>
    <store xmlns="urn:xmpp:hints" />
</message>sent to XMPP

<message xml:lang='en' from='telegram.localhost' to='test@localhost' id='63ac4154bead414aa829cbb1acb3de67'>
    <origin-id id='63ac4154bead414aa829cbb1acb3de67' xmlns='urn:xmpp:sid:0' />
    <body>Error: unlike XMPP, telegram does not allow arbitrary emojis to be used as reactions. The message was: The reaction isn&apos;t available for the message. Please pick your reaction in this list: 👍 👎 ❤ 🔥 🥰 👏 😁 🤔 🤯 😱 🤬 😢 🎉 🤩 🤮 💩 🙏 👌 🕊 🤡 🥱 🥴 😍 🐳 ❤‍🔥 🌚 🌭 💯 🤣</body>
    <request xmlns='urn:xmpp:receipts' />
    <stanza-id by='test@localhost' xmlns='urn:xmpp:sid:0' id='z2F7d3wnV5HVGZVkZaukM48z' />
</message>received

<message xmlns="jabber:client" to="telegram.localhost" type="chat" id="10eb7067-e721-487a-95bf-1e4ea1cc429d">
    <received xmlns="urn:xmpp:receipts" id="63ac4154bead414aa829cbb1acb3de67" />
    <no-store xmlns="urn:xmpp:hints" />
    <no-copy xmlns="urn:xmpp:hints" />
</message>sent to XMPP

<message type='chat' from='test@localhost' to='test@localhost/movimcz1gD9'>
    <sent xmlns='urn:xmpp:carbons:2'>
        <forwarded xmlns='urn:xmpp:forward:0'>
            <message type='chat' from='test@localhost' to='5308963142@telegram.localhost' xmlns='jabber:client'>
                <reactions xmlns='urn:xmpp:reactions:0' id='2402287616' />
                <store xmlns='urn:xmpp:hints' />
                <stanza-id by='test@localhost' xmlns='urn:xmpp:sid:0' id='OtaLiEdxKgCf2rZ1qxGSGN96' />
            </message>
        </forwarded>
    </sent>
</message>received
linker killed 
1482 deconnected
