### ISSUE TITLE
Error: Call to a member function isNotEmpty() on null in Publisher.php

### ISSUE THREAD

**Issue by guillaume-uH57J9** [movim/movim#1123]
Hi ! 

An error occurs when attempting to write a post, when clicking on publish. The daemon crash as a result. 
Versions : movim 0.20, php 7.4, postgresql 13

```
movim[1862380]: movim.ERROR: Error: Call to a member function isNotEmpty() on null in /path/to/movim-git-tag/app/widgets/Publish/Publish.php (line 97)
Trace 
#0 /path/to/movim-git-tag/src/Movim/Widget/Wrapper.php(152): Publish->ajaxPreview() 
#1 /path/to/movim-git-tag/src/Movim/RPC.php(45): Movim\Widget\Wrapper->runWidget() 
#2 /path/to/movim-git-tag/linker.php(190): Movim\RPC->handleJSON() 
#3 /path/to/movim-git-tag/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(123): {closure}() 
#4 /path/to/movim-git-tag/vendor/ratchet/pawl/src/WebSocket.php(72): Ratchet\Client\WebSocket->emit() 
#5 /path/to/movim-git-tag/vendor/ratchet/rfc6455/src/Messaging/MessageBuffer.php(248): Ratchet\Client\WebSocket->Ratchet\Client\{closure}() 
#6 /path/to/movim-git-tag/vendor/ratchet/rfc6455/src/Messaging/MessageBuffer.php(194): Ratchet\RFC6455\Messaging\MessageBuffer->processData() 
#7 /path/to/movim-git-tag/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(123): Ratchet\RFC6455\Messaging\MessageBuffer->onData() 
#8 /path/to/movim-git-tag/vendor/react/stream/src/Util.php(71): Evenement\EventEmitter->emit() 
#9 /path/to/movim-git-tag/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(123): React\Stream\Util::React\Stream\{closure}() 
#10 /path/to/movim-git-tag/vendor/react/stream/src/DuplexResourceStream.php(196): Evenement\EventEmitter->emit() 
#11 /path/to/movim-git-tag/vendor/react/event-loop/src/StreamSelectLoop.php(245): React\Stream\DuplexResourceStream->handleData() 
#12 /path/to/movim-git-tag/vendor/react/event-loop/src/StreamSelectLoop.php(212): React\EventLoop\StreamSelectLoop->waitForStreamActivity() 
#13 /path/to/movim-git-tag/linker.php(330): React\EventLoop\StreamSelectLoop->run() 
#14 {main} [] []

```

**Comment by guillaume-uH57J9** [comment]
Note I noticed this php error when attempting to publish with Firefox. 

When attempting to publish with Chromium I have no php error, but a JS error on the client side : 
```
Snap_snap.js?t=1671397780:186 Uncaught ReferenceError: Upload is not defined
    at Snap_snap.js?t=1671397780:186:1
```

I just upgraded to v0.20, and ran the composer commands to upgrade dependencies, and update the database. 
It's not clear if there's a bug, or if I missed a step.

**Comment by guillaume-uH57J9** [comment]
Thanks for the fix! I applied the patch locally, the daemon no longer crashes when attempting to publish. 

Publishing still doesn't work, I'll try to gather more information on this then report back. 

When pressing "Publish" button, that button is greyed out, and there's a never-ending spinning animation. 
Developers tools show 3 request are sent to some /ws/ endpoint to submit the title, body, and a link attachment. The reply seems valid and confirm the information is "Saved". I see no error message/code. 
Similar behavior in Firefox and Chromium, so I suspect an issue on the server side.
