### ISSUE TITLE
Can't install commit 2988e54e26d18262427fd1f6f7feec6732ba4e84

### ISSUE THREAD

**Issue by tran-h-trung** [movim/movim#1159]
## Behaviour

Can't install from `git clone https://github.com/movim/movim.git`

I follow the instruction in `INSTALL.md` and got to `compose movim:migrate`:
```
www-data@host:~/movim$ composer movim:migrate
> vendor/bin/phinx migrate --ansi
Phinx by CakePHP - https://phinx.org.

using config file phinx.php
using config parser php
using migration paths
 - /var/www/movim/database/migrations
using seed paths
 - /var/www/movim/database/seeds
PHP Deprecated:  default_database in the config has been deprecated since 0.12, use default_environment instead. in /var/www/movim/vendor/robmorgan/phinx/src/Phinx/Config/Config.php on line 223
warning no environment specified, defaulting to: movim
using adapter pgsql
using database movim
ordering by creation time
InvalidArgumentException: Duplicate migration - "/var/www/movim/database/migrations/20180314222244_create_configuration_table.php" has the same version as "2147483647" in /var/www/movim/vendor/robmorgan/phinx/src/Phinx/Migration/Manager.php:783
Stack trace:
#0 /var/www/movim/vendor/robmorgan/phinx/src/Phinx/Migration/Manager.php(313): Phinx\Migration\Manager->getMigrations()
#1 /var/www/movim/vendor/robmorgan/phinx/src/Phinx/Console/Command/Migrate.php(122): Phinx\Migration\Manager->migrate()
#2 /var/www/movim/vendor/symfony/console/Command/Command.php(298): Phinx\Console\Command\Migrate->execute()
#3 /var/www/movim/vendor/symfony/console/Application.php(1040): Symfony\Component\Console\Command\Command->run()
#4 /var/www/movim/vendor/symfony/console/Application.php(301): Symfony\Component\Console\Application->doRunCommand()
#5 /var/www/movim/vendor/robmorgan/phinx/src/Phinx/Console/PhinxApplication.php(70): Symfony\Component\Console\Application->doRun()
#6 /var/www/movim/vendor/symfony/console/Application.php(171): Phinx\Console\PhinxApplication->doRun()
#7 /var/www/movim/vendor/robmorgan/phinx/bin/phinx(28): Symfony\Component\Console\Application->run()
#8 {main}
Script vendor/bin/phinx migrate --ansi handling the movim:migrate event returned with error code 1

```

Also, `composer update`:
```
Package fgrosse/phpasn1 is abandoned, you should avoid using it. No replacement was suggested.
```

I'm running debian stable:
```
PHP 7.4.33 (cli) (built: Nov  8 2022 11:40:37) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.33, Copyright (c), by Zend Technologies
```
## Expectation
Install Movim as the instructed.

**Comment by edhelas** [comment]
I was able the run the complete migrations from the beginning. Looks like you have half-migrated DB somehow.
Please run the migrations again on an empty DB to try again.

**Comment by detrout** [comment]
Hi.

I just got this same error, on an attempted fresh install of movim on Debian 11

```
# sudo -u www-data composer movim:migrate --no-cache -v
> movim:migrate: vendor/bin/phinx migrate --ansi
Phinx by CakePHP - https://phinx.org.

using config file phinx.php
using config parser php
using migration paths 
 - /var/www/movim/database/migrations
using seed paths 
warning no environment specified, defaulting to: movim
using adapter pgsql
using database movim
ordering by creation time
InvalidArgumentException: Duplicate migration - "/var/www/movim/database/migrations/20180314222244_create_configuration_table.php" has the same version as "2147483647" in /var/www/movim/vendor/robmorgan/phinx/src/Phinx/Migration/Manager.php:783
Stack trace:
#0 /var/www/movim/vendor/robmorgan/phinx/src/Phinx/Migration/Manager.php(313): Phinx\Migration\Manager->getMigrations()
#1 /var/www/movim/vendor/robmorgan/phinx/src/Phinx/Console/Command/Migrate.php(122): Phinx\Migration\Manager->migrate()
#2 /var/www/movim/vendor/symfony/console/Command/Command.php(298): Phinx\Console\Command\Migrate->execute()
#3 /var/www/movim/vendor/symfony/console/Application.php(1040): Symfony\Component\Console\Command\Command->run()
#4 /var/www/movim/vendor/symfony/console/Application.php(301): Symfony\Component\Console\Application->doRunCommand()
#5 /var/www/movim/vendor/robmorgan/phinx/src/Phinx/Console/PhinxApplication.php(70): Symfony\Component\Console\Application->doRun()
#6 /var/www/movim/vendor/symfony/console/Application.php(171): Phinx\Console\PhinxApplication->doRun()
#7 /var/www/movim/vendor/robmorgan/phinx/bin/phinx(28): Symfony\Component\Console\Application->run()
#8 {main}
Script vendor/bin/phinx migrate --ansi handling the movim:migrate event returned with error code 1
```

My database is completely empty.

```
# sudo -u postgres psql movim
psql (13.9 (Debian 13.9-0+deb11u1), server 11.12 (Debian 11.12-0+deb10u1))
Type "help" for help.

movim=# \dt
Did not find any relations.
```

The installation method was I git cloned the repository, then checked out with git clone -b live v0.21.1. I set the whole tree to root:root, and them set movim and movim/public to be owned by www-data.

After installing php composer it gave me errors and told me to install php-curl, php-gd, and php-imagick which I did and then composer install did work.

I previously had php-mbstring and php-xml installed.

I thought it might be a permission issue so i also tried chown -R www-data movim, but still have the Duplicate migration error.

**Comment by edhelas** [comment]
This means that the migration was performed but crashed. Please double check that your database is empty. Especially the `phinxlog` table.

**Comment by detrout** [comment]
Thank you for your reply, and it looks like the database is empty.

I stared some at the error message and started trying to run phinx directly.

All my tests trying to directly run migration with various combinations of the -c and -e arguments with ` php vendor/bin/phinx migrate -c phinx.php -e movim --ansi -vvv` or indirectly with `composer movim:migrate` generate the error and leave me with an empty database.

I wondered if it was a connection or permissions issue with psql, if the database connection options in .env weren't making it to phinx, or if there were special characters I need to escape in the .env file, but I resolved my issues connecting to the database with psql and I did manage to get an empty phinxlog table created by using `php vendor/bin/phinx test -e movim` and phinx reported the connection is valid.

```
$ php vendor/bin/phinx test -e movim
Phinx by CakePHP - https://phinx.org.

using config file phinx.php
using config parser php
validating environment movim
success!
```

And after running phinx test there is an empty phinxlog table.
```
movim=# select * from phinxlog;
 version | migration_name | start_time | end_time | breakpoint 
---------+----------------+------------+----------+------------
(0 rows)
```

But `phinx status -e movim` fails with or without the phinxlog table existing. it behaves the same, even if I drop the table phinxlog table.

```
$ php vendor/bin/phinx status -e movim
Phinx by CakePHP - https://phinx.org.

using config file phinx.php
using config parser php
using migration paths 
 - /var/www/movim/database/migrations
using seed paths 
using environment movim
ordering by creation time

In Manager.php line 783:
                                                                                                                         
  Duplicate migration - "/var/www/movim/database/migrations/20180314222244_create_configuration_table.php" has the same  
   version as "2147483647"                                                                                               
                                                                                                                         

status [-c|--configuration CONFIGURATION] [-p|--parser PARSER] [--no-info] [-e|--environment ENVIRONMENT] [-f|--format FORMAT]
```

**Comment by detrout** [comment]
I think I found the issue. the getVersionFromFileName doesn't work with your migration file names on a 32-bit platform.

I added some printf statements to vendor/robmorgan/phinx/src/Phinx/Util/Util.php in getVersionFromFileName

```
        preg_match('/^[0-9]+/', basename($fileName), $matches);
        printf("I LIVE %s\n", basename($fileName));
        foreach($matches as $m) {
          printf("match %s\n", $m);
        }
        $value = (int)($matches[0] ?? null);
        printf("value %s\n", $value);
```

produces

```
I LIVE 20180314212906_create_urls_table.php
match 20180314212906
value 2147483647
```

Note how much bigger "20180314212906" is than the 32-bit max signed int 2147483647

Maybe I should see if I can find newer ewaste for my jabber server.
