### ISSUE TITLE
Error: Call to undefined function opcache_get_status()

### ISSUE THREAD

**Issue by ike08** [movim/movim#1216]
I am setting up a Movim development environment. After I ran `php daemon.php start`, it did not print my daemon websocket proxy configuration. All it displayed was this:

> Please set at least one user as an admin once its account is logged in
To set an existing user admin
php daemon.php setAdmin {jid}
> 
> Movim daemon launched
Base URL: http://192.168.122.108/
Compiled po files
Stickers compiled

The log `movim/log/error.log` displays this: 

> movim.ERROR: Error: Call to undefined function opcache_get_status() in /var/www/movim/app/helpers/UtilsHelper.php (line 96)
Trace
#0 /var/www/movim/src/Movim/Console/DaemonCommand.php(92): isOpcacheEnabled()
#1 /var/www/movim/vendor/symfony/console/Command/Command.php(326): Movim\Console\DaemonCommand->execute()
#2 /var/www/movim/vendor/symfony/console/Application.php(1063): Symfony\Component\Console\Command\Command->run()
#3 /var/www/movim/vendor/symfony/console/Application.php(320): Symfony\Component\Console\Application->doRunCommand()
#4 /var/www/movim/vendor/symfony/console/Application.php(174): Symfony\Component\Console\Application->doRun()
#5 /var/www/movim/daemon.php(20): Symfony\Component\Console\Application->run()
#6 {main}

I ran `grep -rn /var/www/movim/ -e "opcache_get_status"` and it looks like `opcache_get_status()` is not defined anywhere.

**Comment by ike08** [comment]
I installed php-opcache and all is well.
