### ISSUE TITLE
Crash loop on current (2023-July-09) master

### ISSUE THREAD

**Issue by petermolnar** [movim/movim#1219]
I tried to use the current `master`  with current FF, failed, so I tested it with a fresh FF profile, and ended up loop crashing the movim server:

```
[2023-07-09T19:49:10.588476+00:00] movim.ERROR: Error: Call to undefined function App\filter_var() in /usr/local/www/movim/app/Conference.php (line 144)
Trace
#0 /usr/local/www/movim/src/Moxl/Xec/Action/Bookmark2/Get.php(33): App\Conference->set(Object(SimpleXMLElement))
#1 /usr/local/www/movim/src/Moxl/Xec/Handler.php(65): Moxl\Xec\Action\Bookmark2\Get->handle(Object(SimpleXMLElement))
#2 /usr/local/www/movim/linker.php(45): Moxl\Xec\Handler::handle(Object(SimpleXMLElement))
#3 [internal function]: {closure}(Object(SimpleXMLElement))
#4 /usr/local/www/movim/src/Moxl/Parser.php(110): call_user_func_array(Object(Closure), Array)
#5 [internal function]: Moxl\Parser->end(Object(XMLParser), 'iq')
#6 /usr/local/www/movim/src/Moxl/Parser.php(51): xml_parse(Object(XMLParser), 'filiation'/><fe...', false)
#7 /usr/local/www/movim/linker.php(312): Moxl\Parser->parse('filiation'/><fe...')
#8 /usr/local/www/movim/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(123): {closure}('filiation'/><fe...')
#9 /usr/local/www/movim/vendor/react/stream/src/Util.php(71): Evenement\EventEmitter->emit('data', Array)
#10 /usr/local/www/movim/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(123): React\Stream\Util::React\Stream\{closure}('filiation'/><fe...')
#11 /usr/local/www/movim/vendor/react/stream/src/DuplexResourceStream.php(196): Evenement\EventEmitter->emit('data', Array)
#12 /usr/local/www/movim/vendor/react/event-loop/src/StreamSelectLoop.php(246): React\Stream\DuplexResourceStream->handleData(Resource id #346)
#13 /usr/local/www/movim/vendor/react/event-loop/src/StreamSelectLoop.php(213): React\EventLoop\StreamSelectLoop->waitForStreamActivity(379108)
#14 /usr/local/www/movim/linker.php(338): React\EventLoop\StreamSelectLoop->run()
#15 {main}  
```

If I understand the when, how, it crashes after: 
```xml
<pubsub xmlns='http://jabber.org/protocol/pubsub'><items node='urn:xmpp:avatar:data'><item xmlns='http://jabber.org/protocol/pubsub' id='9d78c5c2014aa4900b00feea9e7197c6f5be3359'><data xmlns='urn:xmpp:avatar:data'>
```

 in the daemon log.

**Comment by petermolnar** [comment]
Update: I reverted my setup back to v0.20; this crash loop doesn't happen.

**Comment by edhelas** [comment]
What is happening if you put a "\" in front of "\filter_var", I don't get why this function need to be namespaced.

**Comment by edhelas** [comment]
Any news ? Bump
