### ISSUE TITLE
Chromium: Uncaught DOMException, Uncaught TypeError on every load

### ISSUE THREAD

**Issue by ltguillaume** [movim/movim#1240]
```
Uncaught (in promise) DOMException: Failed to register a ServiceWorker for scope ('https://mov.im/chat/movim%40conference.movim.eu/') with script ('https://mov.im/chat/movim%40conference.movim.eu/sw.js'): The script has an unsupported MIME type ('text/html').
```

and

```
Uncaught TypeError: Cannot read properties of null (reading 'style')
    at movim_base.js:88:19
```

Only on Chromium-based browsers (in my case Ungoogled).
Using https://mov.im

**Comment by edhelas** [comment]
The commit should fix it, please confirm :)

**Comment by ltguillaume** [comment]
The exception is gone.

I still get the type error:
```
Uncaught TypeError: Cannot read properties of null (reading 'style')
    at movim_base.js:88:19
(anonymous) @ movim_base.js:88
```

**Comment by edhelas** [comment]
Did you tried on your own server or on mov.im ? Because the fix was not deployed there.

**Comment by ltguillaume** [comment]
> Did you tried on your own server or on mov.im ? Because the fix was not deployed there.

Ah, just mov.im. It's deployed now, right? No errors anymore.
