### ISSUE TITLE
Replace slash sign with another sign which is compatile with UNIX filesystems

### ISSUE THREAD

**Issue by sjehuda** [movim/movim#1339]
Why do nodes of comments have a slash sign?
Could this sign be replaced by another sign?
```
xmpp:comments.movim.eu?;node=urn:xmpp:microblog:0:comments/4b5e0a74-b4bd-405c-961c-b23d185e78cb
```

[Rivista](https://git.xmpp-it.net/sch/Rivista) is able to read nodes of comments, yet it has failed to open single comment (i.e. item `2d4eee13-6f37-4648-b613-cb8230fefa8d`), because it attempts to write a file with the node `urn:xmpp:microblog:0:comments/4b5e0a74-b4bd-405c-961c-b23d185e78cb` which includes a slash.

Error:
```
961c-b23d185e78cb&item=2d4eee13-6f37-4648-b613-cb8230fefa8d HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/uvicorn/protocols/http/httptools_impl.py", line 411, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/uvicorn/middleware/proxy_headers.py", line 69, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/lib/python3.12/site-packages/starlette/applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/lib/python3.12/site-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/usr/lib/python3.12/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/usr/lib/python3.12/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/usr/lib/python3.12/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/usr/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/lib/python3.12/site-packages/starlette/routing.py", line 756, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/lib/python3.12/site-packages/starlette/routing.py", line 776, in app
    await route.handle(scope, receive, send)
  File "/usr/lib/python3.12/site-packages/starlette/routing.py", line 297, in handle
    await self.app(scope, receive, send)
  File "/usr/lib/python3.12/site-packages/starlette/routing.py", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/usr/lib/python3.12/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/usr/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/lib/python3.12/site-packages/starlette/routing.py", line 72, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/fastapi/routing.py", line 278, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xmpp/rivista/pubsub_to_atom.py", line 112, in view_node_items
    generate_json(iq)
  File "/home/xmpp/rivista/pubsub_to_atom/pubsub_to_atom.py", line 359, in generate_json
    with open(filename, 'w', encoding='utf-8') as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'data/urn:xmpp:microblog:0:comments/4b5e0a74-b4bd-405c-961c-b23d185e78cb.json'
```

Of course, I can encode the sign slash.

**Comment by sjehuda** [comment]
goffi:
> > goffi: Why do nodes of coments have a slash sign? https://github.com/movim/movim/issues/1339
> 
> It's in the spécification: https://xmpp.org/extensions/xep-0277.html#post_comments that can't be changed.
> 
> Anyway all characters can be used in an node id, you need to escape them if you want to use them as file or dir name.

Closing.
