### ISSUE TITLE
Empty contact list

### ISSUE THREAD

**Issue by bachy** [movim/movim#138]
Hello,
i installed movim on my yunohost server (debian 8) with the movim_ynh app https://github.com/movim/movim_ynh
unfortunatly i have some wierd behaviors
The concat list stay desperatly empty. I can add contacts from our domain (esadhar.net) but they never appear on the list.
Yes i configured the list to show disconected contacts
is it a bug ? any idea ?

**Comment by src386** [comment]
Hi, I am the yunohost package maintainer. 
Do you add contacts in Movim or with an external Jabber client ?
Is SSO activated for Movim ?

**Comment by edhelas** [comment]
Hi, thanks for the issue. Do you have the latest movim_ynh update ? You database is also up to date ?

**Comment by edhelas** [comment]
I've tested with the faulty account on MySQL and PostGreSQL and I can reproduce the issue. Please update you Movim package, depdendencies and database.

**Comment by bachy** [comment]
Hello,
i updated the yunohost package by running 

```
yunohost app upgrade movim --url=https://github.com/movim/movim_ynh.git
```

but i still have this issue
trying to connect two users (brand new testing accounts on yunohost on two different browsers), but can't confirm the invitation, just can't click on the gear, nothing append. And if i leave the contact section then back in it, the new contact line has disappeared.

i have js bug on console (firefox)

``` js
TypeError: localStorage.getItem(...) is null
lswidget : localStorage.getItem('username').replace('@', 'at') + '_Notifs',
----------------^
notifs.js (ligne 6, col. 16)
```

``` js
Error: localStorage.getItem(...) is null
@https://esadhar.net/movim/app/widgets/Roster/roster.js:7:24
e@https://esadhar.net/movim/app/widgets/Roster/angular.js:36:313
Ke/this.$get</</<@https://esadhar.net/movim/app/widgets/Roster/angular.js:76:77
M/<@https://esadhar.net/movim/app/widgets/Roster/angular.js:59:85
q@https://esadhar.net/movim/app/widgets/Roster/angular.js:7:426
M@https://esadhar.net/movim/app/widgets/Roster/angular.js:59:69
g@https://esadhar.net/movim/app/widgets/Roster/angular.js:51:409
g@https://esadhar.net/movim/app/widgets/Roster/angular.js:51:426
g@https://esadhar.net/movim/app/widgets/Roster/angular.js:51:426
g@https://esadhar.net/movim/app/widgets/Roster/angular.js:51:426
g@https://esadhar.net/movim/app/widgets/Roster/angular.js:51:426
g@https://esadhar.net/movim/app/widgets/Roster/angular.js:51:426
N/<@https://esadhar.net/movim/app/widgets/Roster/angular.js:51:17
xc/d/</<@https://esadhar.net/movim/app/widgets/Roster/angular.js:18:4
Ue/this.$get</m.prototype.$eval@https://esadhar.net/movim/app/widgets/Roster/angular.js:126:246
Ue/this.$get</m.prototype.$apply@https://esadhar.net/movim/app/widgets/Roster/angular.js:126:471
xc/d/<@https://esadhar.net/movim/app/widgets/Roster/angular.js:17:477
e@https://esadhar.net/movim/app/widgets/Roster/angular.js:36:313
xc/d@https://esadhar.net/movim/app/widgets/Roster/angular.js:17:1
xc@https://esadhar.net/movim/app/widgets/Roster/angular.js:18:179
Od@https://esadhar.net/movim/app/widgets/Roster/angular.js:17:1
@https://esadhar.net/movim/app/widgets/Roster/angular.js:251:429
a@https://esadhar.net/movim/app/widgets/Roster/angular.js:165:93
qf/c@https://esadhar.net/movim/app/widgets/Roster/angular.js:32:384

...tack:a.sourceURL&&(a=a.message+"\n"+a.sourceURL+":"+a.line));return a}function e...

angular.js (ligne 102)
```

``` js
Error caught: TypeError: angular.element(...).scope(...).initContacts is not a function - initContacts:["[]"]
movim_w...cket.js (ligne 147)
```

``` js
Error caught: TypeError: angular.element(...).scope(...).initGroups is not a function - initGroups:["[]"]
movim_w...cket.js (ligne 147)
```

``` js
Error caught: TypeError: angular.element(...).scope(...).updateContact is not a function - updateContact:["{\"jid\":\"bachir@esadhar.net\",\"rostername\":\"bachir@esadhar.net\",\"groupname\":\"D\\u00e9group\\u00e9\",\"status\":\"Working hard to convert Art School Students to liberty (of free and open source software)\",\"resource\":\"moxlwBiFYv\",\"value\":1,\"rosterview\":{\"avatar\":\"https:\\/\\/esadhar.net\\/movim\\/cache\\/9f574caa681a78acb9d7439ef2c51b7a_50.jpg\",\"color\":\"blue\",\"name\":\"Bachir Soussi Chiadmi\",\"friendpage\":\"https:\\/\\/esadhar.net\\/movim\\/?contact\\/bachir@esadhar.net\",\"subscription\":\"to\",\"inactive\":\"\",\"presencetxt\":\"online\",\"type\":\"web\",\"client\":\"movim\",\"jingle\":true,\"tune\":false}}"]
movim_w...cket.js (ligne 147)
```

**Comment by edhelas** [comment]
Hi, thanks for the report. Does localStorage is enabled on this browser ?

**Comment by bachy** [comment]
yes local storage is activated and working, i can inspect it with web inspector.

The errors on my last post were from firefox where i can't event click on the gear.

On chromium i can click on the gear to accept the invitation, but the contact does not appears on contact list.
I have also others error messages on chromium console

``` js
Failed to parse SourceMap: https://esadhar.net/movim/app/widgets/Roster/angular.min.js.map
movim_websocket.js:53 Connection established!
```

**Comment by src386** [comment]
edhelas commited a fix for movim, it's available in movim_ynh in the dev branch.

To install : 

```
git clone https://github.com/movim/movim_ynh
cd movim_ynh
git checkout -b dev origin/dev
yunohost app upgrade movim -f .
```

**Comment by bachy** [comment]
hello,
thanks for the patch, i upgarded movim on my ynh instance as explained above but now i can't access movim any more.
connect to ynh then click on movim, end to movim/?disconnect

/var/www/movim/log/php.log

``` log
[15-Mar-2016 10:36:32 Europe/Paris] PHP Fatal error:  Class 'React\SocketClient\TcpConnector' not found in /var/www/movim/linker.php on line 16
[15-Mar-2016 10:36:32 Europe/Paris] PHP Fatal error:  Uncaught exception 'Exception' in /var/www/movim/system/Route.php:93
Stack trace:
#0 /var/www/movim/system/controllers/BaseController.php(55): Route::urlize('')
#1 /var/www/movim/app/controllers/DisconnectController.php(11): BaseController->redirect('')
#2 /var/www/movim/system/controllers/FrontController.php(54): DisconnectController->dispatch()
#3 /var/www/movim/system/controllers/FrontController.php(22): FrontController->runRequest('disconnect')
#4 /var/www/movim/index.php(53): FrontController->handle()
#5 {main}
  thrown in /var/www/movim/system/Route.php on line 93
[15-Mar-2016 10:36:32 Europe/Paris] PHP Fatal error:  Class 'React\SocketClient\TcpConnector' not found in /var/www/movim/linker.php on line 16
[15-Mar-2016 10:36:32 Europe/Paris] PHP Fatal error:  Uncaught exception 'Exception' in /var/www/movim/system/Route.php:93
Stack trace:
#0 /var/www/movim/system/controllers/BaseController.php(55): Route::urlize('')
#1 /var/www/movim/app/controllers/DisconnectController.php(11): BaseController->redirect('')
#2 /var/www/movim/system/controllers/FrontController.php(54): DisconnectController->dispatch()
#3 /var/www/movim/system/controllers/FrontController.php(22): FrontController->runRequest('disconnect')
#4 /var/www/movim/index.php(53): FrontController->handle()
#5 {main}
  thrown in /var/www/movim/system/Route.php on line 93
```

**Comment by src386** [comment]
huh ? strange.
can you clear your browser cache ?
If it does not works, try to delete then reinstall movim (from the movim_ynh dev)

**Comment by bachy** [comment]
ok i removed movim but i dont know how to install it from a local folder ( sorry :/ )
i tried `yunohost app install movim /home/bach/movim_ynh/`

never mind i made it `yunohost app install /home/bach/movim_ynh/`

**Comment by src386** [comment]
```
cd movim_ynh
yunohost app install .
```

**Comment by bachy** [comment]
seems to be wors

``` log
[15-Mar-2016 11:07:29 Europe/Paris] PHP Fatal error:  Class 'Modl\Modl' not found in /var/www/movim/bootstrap.php on line 299
```

i tried then to remove the app again, reinstall it from github, then run again the upgrade from dev, same result.

**Comment by src386** [comment]
```
yunohost app remove movim
cd movim_ynh
git branch (make sure it's "dev")
git pull
yunohost app install .
```

**Comment by bachy** [comment]
```
$ git remote -v
origin  https://github.com/movim/movim_ynh (fetch)
origin  https://github.com/movim/movim_ynh (push)

$ git pull origin dev
From https://github.com/movim/movim_ynh
 * branch            dev        -> FETCH_HEAD
Already up-to-date.
```

**Comment by src386** [comment]
Ok, I justed fixed a bug.
Can you do it again ? pull the dev then install/upgrade.

**Comment by bachy** [comment]
ok, it works now
thank you !!
