### ISSUE TITLE
Unable to start daemon.php

### ISSUE THREAD

**Issue by ghost** [movim/movim#143]
Hello there,

I'm very happy to see the many improvements realized with Movim, thanks!
I got a strange problem when I try to launch the daemon:

```
10:22 > php daemon.php                                                                                                                                      

        <div style="font-family: Arial; text-align: center;">
            <h2>Oops... something went wrong.</h2>
            <p>But don't panic. The NSA is on the case.</p>
        </div>
```

Everything was fine on the installation process, and the logs tell me that:

```
thrown in /srv/htdocs/movim.unixcorn.org/movim/vendor/movim/modl/src/Modl/Modl.php on line 127
[07-Mar-2016 10:15:16 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] No such file or directory' in /srv/htdocs/movim.unixcorn.org/movim/vendor/movim/modl/src/Modl/Modl.php:127
Stack trace:
#0 /srv/htdocs/movim.unixcorn.org/movim/vendor/movim/modl/src/Modl/Modl.php(127): PDO->__construct('mysql:host=loca...', 'XXXXXXX', 'XXXXXXXX...', Array)
#1 /srv/htdocs/movim.unixcorn.org/movim/bootstrap.php(328): Modl\Modl->connect()
#2 /srv/htdocs/movim.unixcorn.org/movim/bootstrap.php(64): Bootstrap->loadModl()
#3 /srv/htdocs/movim.unixcorn.org/movim/daemon.php(17): Bootstrap->boot()
#4 {main}
```

Don't understand what I need to do.
Hope somebody can help.

**Comment by ghost** [comment]
Sorry, duplicate issue.
