### ISSUE TITLE
Skype transport quotes causing web UI to crash

### ISSUE THREAD

**Issue by pztrn** [movim/movim#150]
When using Skype transport with Spectrum2 receiving quotes causing web UI to crash and logout.

Example quote:

```
<quote author="username" authorname="User Name" conversation="myaccountname" guid="somerandomid" timestamp="1457499703"><legacyquote>[11:01:43] User Name: LOL :D<legacyquote>
```

Logs:

```
[09-Mar-2016 10:01:47 Asia/Yekaterinburg] PHP Fatal error:  Uncaught exception 'Exception' with message 'String could not be parsed as XML' in /data/WWW/pztrn.name/movim/public/app/models/message/Message.php:102
Stack trace:
#0 /data/WWW/pztrn.name/movim/public/app/models/message/Message.php(102): SimpleXMLElement->__construct('<body xmlns="ht...')
#1 /data/WWW/pztrn.name/movim/public/vendor/movim/moxl/src/Moxl/Xec/Payload/Carbons.php(48): modl\Message->set(Object(SimpleXMLElement), Object(SimpleXMLElement))
#2 /data/WWW/pztrn.name/movim/public/vendor/movim/moxl/src/Moxl/Xec/Handler.php(224): Moxl\Xec\Payload\Carbons->handle(Object(SimpleXMLElement), Object(SimpleXMLElement))
#3 /data/WWW/pztrn.name/movim/public/vendor/movim/moxl/src/Moxl/Xec/Handler.php(152): Moxl\Xec\Handler::searchPayload('201fa54dd93e340...', Object(SimpleXMLElement), Object(SimpleXMLElement))
#4 /data/WWW/pztrn.name/movim/public/vendor/movim/moxl/src/Moxl/Xec/Handler.php(68): Moxl\Xec\Handler::handleNode(Object(SimpleXMLElement), Object(SimpleXMLElement))
#5 /data/WWW/pztrn.name/movim/public/vend in /data/WWW/pztrn.name/movim/public/app/models/message/Message.php on line 102
[09-Mar-2016 10:14:10 Asia/Yekaterinburg] PHP Fatal error:  Uncaught exception 'Exception' with message 'String could not be parsed as XML' in /data/WWW/pztrn.name/movim/public/app/models/message/Message.php:102
Stack trace:
#0 /data/WWW/pztrn.name/movim/public/app/models/message/Message.php(102): SimpleXMLElement->__construct('<body xmlns="ht...')
#1 /data/WWW/pztrn.name/movim/public/vendor/movim/moxl/src/Moxl/Xec/Payload/Carbons.php(48): modl\Message->set(Object(SimpleXMLElement), Object(SimpleXMLElement))
#2 /data/WWW/pztrn.name/movim/public/vendor/movim/moxl/src/Moxl/Xec/Handler.php(224): Moxl\Xec\Payload\Carbons->handle(Object(SimpleXMLElement), Object(SimpleXMLElement))
#3 /data/WWW/pztrn.name/movim/public/vendor/movim/moxl/src/Moxl/Xec/Handler.php(152): Moxl\Xec\Handler::searchPayload('201fa54dd93e340...', Object(SimpleXMLElement), Object(SimpleXMLElement))
#4 /data/WWW/pztrn.name/movim/public/vendor/movim/moxl/src/Moxl/Xec/Handler.php(68): Moxl\Xec\Handler::handleNode(Object(SimpleXMLElement), Object(SimpleXMLElement))
#5 /data/WWW/pztrn.name/movim/public/vend in /data/WWW/pztrn.name/movim/public/app/models/message/Message.php on line 102
[09-Mar-2016 10:25:43 Asia/Yekaterinburg] PHP Fatal error:  Call to a member function close() on resource in /data/WWW/pztrn.name/movim/public/linker.php on line 67
[09-Mar-2016 10:30:36 Asia/Yekaterinburg] PHP Fatal error:  Uncaught exception 'Exception' with message 'String could not be parsed as XML' in /data/WWW/pztrn.name/movim/public/app/models/message/Message.php:102
Stack trace:
#0 /data/WWW/pztrn.name/movim/public/app/models/message/Message.php(102): SimpleXMLElement->__construct('<body xmlns="ht...')
#1 /data/WWW/pztrn.name/movim/public/vendor/movim/moxl/src/Moxl/Xec/Payload/MAMResult.php(10): modl\Message->set(Object(SimpleXMLElement), Object(SimpleXMLElement))
#2 /data/WWW/pztrn.name/movim/public/vendor/movim/moxl/src/Moxl/Xec/Handler.php(224): Moxl\Xec\Payload\MAMResult->handle(Object(SimpleXMLElement), Object(SimpleXMLElement))
#3 /data/WWW/pztrn.name/movim/public/vendor/movim/moxl/src/Moxl/Xec/Handler.php(152): Moxl\Xec\Handler::searchPayload('0977b7387b95f69...', Object(SimpleXMLElement), Object(SimpleXMLElement))
#4 /data/WWW/pztrn.name/movim/public/vendor/movim/moxl/src/Moxl/Xec/Handler.php(68): Moxl\Xec\Handler::handleNode(Object(SimpleXMLElement), Object(SimpleXMLElement))
#5 /data/WWW/pztrn.name/movim/public/ in /data/WWW/pztrn.name/movim/public/app/models/message/Message.php on line 102
```

**Comment by edhelas** [comment]
Thanks for the report, it seems that your XML is not valid (you're missing the </quote>) ?

**Comment by edhelas** [comment]
Can you please try again with the latest trunk ?

**Comment by edhelas** [comment]
Hi, do you still have the issue ? If not I'm considering this ticket as resolved.

**Comment by pztrn** [comment]
Hello and sorry for late response. I'll try to test it within next 2 days, I'm not near PC now.

**Comment by pztrn** [comment]
Sorry for late response, but no, it still crashes, with same error message.

**Comment by pztrn** [comment]
Ops, sorry, just re-tested with right now's git clone, and now it doesn't crash.
