### ISSUE TITLE
start movim daemon error: The NSA is on the case.

### ISSUE THREAD

**Issue by zyfmix** [movim/movim#235]
when i followed [Install Movim](https://github.com/movim/movim/wiki/Install-Movim#2-database-configuration) and start movim like below:

``` php
yzhang@coam:~/ServerCoam/WebMovIM$ sudo -s -u www-data
www-data@coam:~/ServerCoam/WebMovIM$ php daemon.php https://mim.coopens.com 443

Oops... something went wrong.
But don't panic. The NSA is on the case.
```

i do not know what's wrong!my nginx server config like below:

``` php
server {
    listen 80;
    listen 443 ssl http2; ## listen for ipv4; this line is default and implied
    #listen   [::]:80 default ipv6only=on; ## listen for ipv6

    #root /usr/share/nginx/www;
    set $root_path /data/home/yzhang/ServerCoam/WebMovIM/;
    root $root_path;
    index index.php index.html index.htm;

    # Make site accessible from http://localhost/
    server_name mim.coopens.com;

    location /ws/ {
        proxy_pass https://mim.coopens.com:443/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
        proxy_redirect off;
    }

    ...
}
```

when i open https://mim.coopens.com/ .it console error like below:

``` javascript
SyntaxError: expected expression, got ';'
var SECURE_WEBSOCKET= ;

ReferenceError: SECURE_WEBSOCKET is not defined
if(SECURE_WEBSOCKET) {
```

I do not know what's wrong,who can help me?

**Comment by zyfmix** [comment]
``` php
www-data@coam:~/ServerCoam/WebMovIM$ php daemon.php http://mim.coopens.com 443

Array
(
    [type] => 1
    [message] => Uncaught PDOException: SQLSTATE[HY000] [2002] No such file or directory in /data/home/yzhang/ServerCoam/WebMovIM/vendor/movim/modl/src/Modl/Modl.php:124
Stack trace:
#0 /data/home/yzhang/ServerCoam/WebMovIM/vendor/movim/modl/src/Modl/Modl.php(124): PDO->__construct('mysql:host=loca...', 'zhangyanxi', 'yanxi312', Array)
#1 /data/home/yzhang/ServerCoam/WebMovIM/src/Movim/Bootstrap.php(295): Modl\Modl->connect()
#2 /data/home/yzhang/ServerCoam/WebMovIM/src/Movim/Bootstrap.php(27): Movim\Bootstrap->loadModl()
#3 /data/home/yzhang/ServerCoam/WebMovIM/daemon.php(20): Movim\Bootstrap->boot()
#4 {main}
  thrown
    [file] => /data/home/yzhang/ServerCoam/WebMovIM/vendor/movim/modl/src/Modl/Modl.php
    [line] => 124
)
Oops... something went wrong.
But don't panic. The NSA is on the case.
```
