### ISSUE TITLE
PHP Fatal error:  Uncaught Exception: Could not gather sufficient random data

### ISSUE THREAD

**Issue by ghost** [movim/movim#354]
Since updating Archlinux (to php 7.1.2-) I get:

`PHP Fatal error:  Uncaught Exception: Could not gather sufficient random data in /srv/movim/vendor/ramsey/uuid/src/Generator/RandomBytesGenerator.php:34
Stack trace:
#0 /srv/movim/vendor/ramsey/uuid/src/Generator/RandomBytesGenerator.php(34): random_bytes(16)
#1 /srv/movim/vendor/ramsey/uuid/src/UuidFactory.php(217): Ramsey\Uuid\Generator\RandomBytesGenerator->generate(16)
#2 /srv/movim/vendor/ramsey/uuid/src/Uuid.php(674): Ramsey\Uuid\UuidFactory->uuid4()
#3 /srv/movim/app/widgets/Chat/Chat.php(285): Ramsey\Uuid\Uuid::uuid4()
#4 [internal function]: Chat->ajaxSendMessage('XXX...', 'XXX...', false, NULL, NULL)
#5 /srv/movim/src/Movim/Widget/Wrapper.php(138): call_user_func_array(Array, Array)
#6 /srv/movim/system/RPC.php(87): Movim\Widget\Wrapper->runWidget('Chat', 'ajaxSendMessage', Array)
#7 /srv/movim/linker.php(172): RPC->handle_json(Object(stdClass))
#8 [internal function]: {closure}('{"func":"messag...', Object(React\Stream\Stream))
#9 /srv/movim/vendor/evenement/evenement/src/Evenement/EventEmitterTrait. in /srv/movim/vendor/ramsey/uuid/src/Generator/RandomBytesGenerator.php on line 34
`

Now, I'm not able to post anything in movim... I just get logged out, when i try to write to anybody...

I think its [this Bug in ramsey/uuid](https://github.com/ramsey/uuid/issues/156).

There also is a temporary fix for this error, (downgrade or compile php for yourself), i will try it out tonight... :)
cheers

**Comment by ghost** [comment]
I had to downgrade to php-7.0.14 to get it work again. It's because my old kernel does not support getrandom() in php7.1, but this version of ramsey/uuid relies on it. 
Thanks
