### ISSUE TITLE
Crash when trying to access certain PubSub servers

### ISSUE THREAD

**Issue by MRZA-MRZA** [movim/movim#545]
When I try to browse pubsub servers on movim.eu in "COMMUNITIES SERVERS" tab Movim logs me out.
I get following error in Movim log file:
```
[07-Dec-2017 22:02:36 UTC] PHP Fatal error:  Uncaught Error: Call to a member function getPubsubRoles() on null in /var/www/movim/app/widgets/CommunityAffiliations/CommunityAffiliations.php:62
Stack trace:
#0 /var/www/movim/src/Movim/Widget/Wrapper.php(183): CommunityAffiliations->onAffiliations(Object(Moxl\Xec\Payload\Packet))
#1 /var/www/movim/vendor/movim/moxl/src/Moxl/Xec/Payload/Payload.php(97): Movim\Widget\Wrapper->iterate('disco_request_a...', Object(Moxl\Xec\Payload\Packet))
#2 /var/www/movim/vendor/movim/moxl/src/Moxl/Xec/Payload/Payload.php(86): Moxl\Xec\Payload\Payload->event('disco_request_a...', Object(Moxl\Xec\Payload\Packet))
#3 /var/www/movim/vendor/movim/moxl/src/Moxl/Xec/Action/Disco/Request.php(96): Moxl\Xec\Payload\Payload->deliver()
#4 /var/www/movim/vendor/movim/moxl/src/Moxl/Xec/Handler.php(118): Moxl\Xec\Action\Disco\Request->handle(Object(SimpleXMLElement))
#5 /var/www/movim/linker.php(27): Moxl\Xec\Handler::handle(Object(SimpleXMLElement))
#6 [internal function]: {closure}(Object(SimpleXMLElement))
#7 /var/www/movim/vendor/mov in /var/www/movim/app/widgets/CommunityAffiliations/CommunityAffiliations.php on line 62
```

**Comment by mitchellurgero** [comment]
I also have this issue on master branch. Would be nice to see a fix soon.
