### ISSUE TITLE
Crash loading chat rooms on first try after login

### ISSUE THREAD

**Issue by Natureshadow** [movim/movim#589]
I get the following error when I login to my Movim pod, causing it to reload and relogin. On second try, it works (or the MUC causing it is not reloaded):

```
Jan 17 21:39:04 commu movim[4880]: movim.ERROR: Uncaught Error: Call to a member function checkConnected() on null in /var/www/movim/cache/_chat.c8c055d6113ec2501dd842d78e18da57.rtpl.php:4 
Stack trace: #0 /var/www/movim/vendor/rain/raintpl/library/Rain/Tpl.php(63): require() 
#1 /var/www/movim/app/widgets/Chat/Chat.php(592): Rain\Tpl->draw('_chat', true) 
#2 /var/www/movim/app/widgets/Chat/Chat.php(245): Chat->prepareChat('#!\\\\2fbin\\\\2fmk...', true) 
#3 /var/www/movim/app/widgets/Chat/Chat.php(160): Chat->ajaxGetRoom('#!\\2fbin\\2fmksh...') 
#4 /var/www/movim/src/Movim/Widget/Wrapper.php(174): Chat->onMucConnected(Object(Moxl\Xec\Payload\Packet))
#5 /var/www/movim/vendor/movim/moxl/src/Moxl/Xec/Payload/Payload.php(97): Movim\Widget\Wrapper->iterate('presence_muc_ha...', Object(Moxl\Xec\Payload\Packet)) 
#6 /var/www/movim/vendor/movim/moxl/src/Moxl/Xec/Payload/Payload.php(86): Moxl\Xec\Payload\Payload->event('presence_muc_ha...', Object(Moxl\Xec\Payload\Packet)) 
#7 /var/www/movim/vendor/movim/moxl/src/Moxl/Xec/Payload/Presence.php(60): Moxl\Xec\Payload\Paylo [] []
```

Funnily, Salut a toi in the current stable release throws a very similar exception (the current hg master doesn't). Thus, I assume it is something to do with one of my chatrooms…

**Comment by edhelas** [comment]
Hi, is it still happening :) ?

**Comment by Natureshadow** [comment]
I will have to test without the local patch you sent me, but can only do so on Monday.

**Comment by Natureshadow** [comment]
Seems gone.
