### ISSUE TITLE
Uncaught error on loading rooms after Eloquent update

### ISSUE THREAD

**Issue by Natureshadow** [movim/movim#619]
After upgrading to the eloquent version, Movim fails to load with the following exception:

```
Apr 17 13:33:17 commu movim[27808]: movim.ERROR: Uncaught Error: Call to a member function conferences() on null in /var/www/movim/app/widgets/Rooms/Rooms.php:351 Stack trace: 
#0 /var/www/movim/app/widgets/Rooms/Rooms.php(94): Rooms->prepareRooms(NULL) 
#1 /var/www/movim/app/widgets/Rooms/Rooms.php(103): Rooms->refreshRooms(NULL) 
#2 /var/www/movim/src/Movim/Widget/Wrapper.php(147): Rooms->ajaxDisplay(NULL) 
#3 /var/www/movim/src/Movim/RPC.php(27): Movim\Widget\Wrapper->runWidget('Rooms', 'ajaxDisplay', Array) 
#4 /var/www/movim/linker.php(106): Movim\RPC->handleJSON(Object(stdClass)) 
#5 /var/www/movim/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(123): {closure}(Object(stdClass)) 
#6 /var/www/movim/vendor/react/zmq/src/SocketWrapper.php(91): Evenement\EventEmitter->emit('message', Array) 
#7 /var/www/movim/vendor/react/zmq/src/SocketWrapper.php(76): React\ZMQ\SocketWrapper->handleReadEvent() 
#8 [internal function]: React\ZMQ\SocketWrapper->handleEvent(Resource id #200) 
#9 /var/www/movim/vendor/react/event-loop/src/StreamSelectLoop.php(238): call [] []

```

**Comment by Natureshadow** [comment]
It works on a second try and after waiting several minutes.
