### ISSUE TITLE
Unique violation on posting

### ISSUE THREAD

**Issue by Natureshadow** [movim/movim#622]
When posting a news post, I got this error three times in a row (for the same post):

```
Apr 18 09:42:48 commu movim[24235]: movim.ERROR:
Uncaught PDOException: SQLSTATE[23505]: Unique violation: 7
ERROR:  duplicate key value violates unique constraint "posts_server_node_nodeid_unique"
DETAIL:  Key (server, node, nodeid)=(nik@mercurius.teckids.org, urn:xmpp:microblog:0, bundescloud-open-source-mit-nextcloud-statt-dropbox-oder-google-drive-wkcIWM) already exists.
in /var/www/movim/vendor/illuminate/database/Connection.php:330 
Stack trace: 
#0 /var/www/movim/vendor/illuminate/database/Connection.php(330): PDOStatement->execute() 
#1 /var/www/movim/vendor/illuminate/database/Connection.php(657): Illuminate\Database\Connection->Illuminate\Database\{closure}('insert into "po...', Array) 
#2 /var/www/movim/vendor/illuminate/database/Connection.php(624): Illuminate\Database\Connection->runQueryCallback('insert into "po...', Array, Object(Closure)) 
#3 /var/www/movim/vendor/illuminate/database/Connection.php(333): Illuminate\Database\Connection->run('insert into "po...', Array, Object(Closure)) 
#4 /var/www/movim/vendor/illuminate/database/Connection.php(30 [] []
```

**Comment by edhelas** [comment]
I've just pushed a fix, for Post crash related issues. https://github.com/movim/movim/commit/a7449b5860a9eaa0e537ad1945f46e97e09767f2

**Comment by edhelas** [comment]
As I didn't got any feedback on this ticket, I'm closing it :)
