### ISSUE TITLE
Not-null violation in user_id

### ISSUE THREAD

**Issue by Natureshadow** [movim/movim#628]
Using 977557d871bc922d57045d2c21d3bfa79666869d:

```
Apr 19 15:20:20 commu movim[1570]: movim.ERROR: Uncaught PDOException: SQLSTATE[23502]: Not null violation: 7 ERROR:  null value in column "user_id" violates not-null constraint
DETAIL:  Failing row contains (null, since, eJwrtjK0tFIyMjC00DUw0TW0VDA0tjIyACIlawBQ1AWA, 2018-04-19 13:20:20, 2018-04-19 13:20:20).
in /var/www/movim/vendor/illuminate/database/Connection.php:458 Stack trace:
#0 /var/www/movim/vendor/illuminate/database/Connection.php(458): PDOStatement->execute() 
#1 /var/www/movim/vendor/illuminate/database/Connection.php(657): Illuminate\Database\Connection->Illuminate\Database\{closure}('insert into "ca...', Array) 
#2 /var/www/movim/vendor/illuminate/database/Connection.php(624): Illuminate\Database\Connection->runQueryCallback('insert into "ca...', Array, Object(Closure)) 
#3 /var/www/movim/vendor/illuminate/database/Connection.php(459): Illuminate\Database\Connection->run('insert into "ca...', Array, Object(Closure)) 
#4 /var/www/movim/vendor/illuminate/database/Connection.php(411): Illuminate\Database\Connection->statement('insert into "ca...' [] []
```

Happens at seemingly random points.

**Comment by Natureshadow** [comment]
Interestringly, the most recent post where this happened on posting is one of those affected by #625.

**Comment by Natureshadow** [comment]
Also happens at login now.

**Comment by Natureshadow** [comment]
Seems gone.
