### ISSUE TITLE
PHP Fatal error on connect.

### ISSUE THREAD

**Issue by alexandrelb** [movim/movim#663]
Hello! I install movim from git. When I try to connect to my XMPP account i got this error :

```
PHP Fatal error:  Uncaught Error: Call to a member function contacts() on null in /var/www/movim/app/widgets/ContactHeader/ContactHeader.php:83
Stack trace:
#0 /var/www/movim/app/widgets/ContactHeader/ContactHeader.php(22): ContactHeader->prepareHeader(NULL)
#1 /var/www/movim/src/Movim/Widget/Wrapper.php(181): ContactHeader->onUpdate(Object(Moxl\Xec\Payload\Packet))
#2 /var/www/movim/lib/moxl/src/Moxl/Xec/Payload/Payload.php(102): Movim\Widget\Wrapper->iterate('roster_getlist_...', Object(Moxl\Xec\Payload\Packet))
#3 /var/www/movim/lib/moxl/src/Moxl/Xec/Payload/Payload.php(91): Moxl\Xec\Payload\Payload->event('roster_getlist_...', Object(Moxl\Xec\Payload\Packet))
#4 /var/www/movim/lib/moxl/src/Moxl/Xec/Action/Roster/GetList.php(31): Moxl\Xec\Payload\Payload->deliver()
#5 /var/www/movim/lib/moxl/src/Moxl/Xec/Handler.php(120): Moxl\Xec\Action\Roster\GetList->handle(Object(SimpleXMLElement))
#6 /var/www/movim/linker.php(26): Moxl\Xec\Handler::handle(Object(SimpleXMLElement))
#7 [internal function]: {closure}(Object(SimpleXMLEleme in /var/www/movim/app/widgets/ContactHeader/ContactHeader.php on line 83
```

I use apache2 and php7. this error make movim loop on login and home page.

**Comment by alexandrelb** [comment]
It work since https://github.com/movim/movim/commit/a0ac6153f43a69be36e3d4bcb68075c0b4bd6e33
Thank you!
