### ISSUE TITLE
Error deploying movim_movim

### ISSUE THREAD

**Issue by amirkhonov** [movim/movim#673]
I got an error when deploying movim to clean Debian 9.4:
```
Stack trace:
#0 /var/www/movim/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php(105): PDOStatement->execute(NULL)
#1 /var/www/movim/vendor/illuminate/database/Connection.php(330): Doctrine\DBAL\Driver\PDOStatement->execute()
#2 /var/www/movim/vendor/illuminate/database/Connection.php(657): Illuminate\Database\Connection->Illuminate\Database\{closure}('select * from "...', Array)
#3 /var/www/movim/vendor/illuminate/database/Connection.php(624): Illuminate\Database\Connection->runQueryCallback('select * from "...', Array, Object(Closure))
#4 /var/www/movim/vendor/illuminate/database/Connection.php(333): Illuminate\Database\Connection->run('select * from "...', Array, Object(Closure))
#5 /var/www/movim/vendor/illumi
in /var/www/movim/vendor/illuminate/database/Connection.php (line 664)
Could not open input file: mud.php
Could not open input file: mud.php

Oops... something went wrong.
Uncaught PDOException: SQLSTATE[42P01]: Undefined table: 7 ERROR:  relation "configuration" does not exist
LINE 1: select * from "configuration" where "configuration"."id" = $...
                      ^ in /var/www/movim/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:105
```

**Comment by edhelas** [comment]
Did you follow [the tutorial](https://github.com/movim/movim/wiki/Install-Movim)? Which version? mud.php doesn't exists anymore.

**Comment by edhelas** [comment]
Closing the ticket as it seems to be a deployment mistake.
