### ISSUE TITLE
Stack trace when reading from user session

### ISSUE THREAD

**Issue by JKingweb** [movim/movim#674]
It seems like Movim may not be correctly initializing the user session.  I get the following stack trace in my logs:

```
[27-Jun-2018 17:39:39 UTC] PHP Fatal error:  Uncaught Error: Call to a member function contacts() on null in /usr/share/movim/app/widgets/Chat/Chat.php:586
Stack trace:
#0 /usr/share/movim/app/widgets/Chat/Chat.php(229): Chat->prepareChat('***JID***')
#1 /usr/share/movim/src/Movim/Widget/Wrapper.php(142): Chat->ajaxGet('***JID***')
#2 /usr/share/movim/src/Movim/RPC.php(27): Movim\Widget\Wrapper->runWidget('Chat', 'ajaxGet', Array)
#3 /usr/share/movim/linker.php(106): Movim\RPC->handleJSON(Object(stdClass))
#4 /usr/share/movim/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(123): {closure}(Object(stdClass))
#5 /usr/share/movim/vendor/react/zmq/src/SocketWrapper.php(91): Evenement\EventEmitter->emit('message', Array)
#6 /usr/share/movim/vendor/react/zmq/src/SocketWrapper.php(76): React\ZMQ\SocketWrapper->handleReadEvent()
#7 [internal function]: React\ZMQ\SocketWrapper->handleEvent(Resource id #205)
#8 /usr/share/movim/vendor/react/event-loop/src/StreamSelectLoop.php(238): call_user_func(Array, Resource id #205)
#9 /usr/sh in /usr/share/movim/app/widgets/Chat/Chat.php on line 586
```

I also get the following notices:

```
[27-Jun-2018 17:30:18 UTC] PHP Notice:  Trying to get property 'id' of non-object in /usr/share/movim/app/widgets/ContactDisco/ContactDisco.php on line 34
```

In both cases the non-object is the widget's `$this->user->session` property. I tried to trace where the session was getting initialized, but was unable to confirm that this ever actually occurs.

**Comment by edhelas** [comment]
I made some changes regarding session management in Movim recently.
Are you still experiencing those kind of issues?

**Comment by JKingweb** [comment]
I still get the same fatal error, though the stack trace now differs slightly:

```
[11-Jul-2018 21:47:42 UTC] PHP Fatal error:  Uncaught Error: Call to a member function contacts() on null in /usr/share/movim/app/widgets/Chat/Chat.php:584
Stack trace:
#0 /usr/share/movim/app/widgets/Chat/Chat.php(228): Chat->prepareChat('***JID***')
#1 /usr/share/movim/src/Movim/Widget/Wrapper.php(142): Chat->ajaxGet('***JID***')
#2 /usr/share/movim/src/Movim/RPC.php(27): Movim\Widget\Wrapper->runWidget('Chat', 'ajaxGet', Array)
#3 /usr/share/movim/linker.php(112): Movim\RPC->handleJSON(Object(stdClass))
#4 /usr/share/movim/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(123): {closure}(Object(stdClass))
#5 /usr/share/movim/vendor/react/zmq/src/SocketWrapper.php(91): Evenement\EventEmitter->emit('message', Array)
#6 /usr/share/movim/vendor/react/zmq/src/SocketWrapper.php(76): React\ZMQ\SocketWrapper->handleReadEvent()
#7 /usr/share/movim/vendor/react/event-loop/src/StreamSelectLoop.php(238): React\ZMQ\SocketWrapper->handleEvent(Resource id #221)
#8 /usr/share/movim/vendor/react/event-loop/src/StreamSelectLoop.php(205): in /usr/share/movim/app/widgets/Chat/Chat.php on line 584
```

I now also get the following notice, which is obviously related:

```
[11-Jul-2018 21:47:42 UTC] PHP Notice:  Trying to get property 'host' of non-object in /usr/share/movim/app/widgets/Chat/Chat.php on line 566
```

**Comment by JKingweb** [comment]
Confirmed as an ejabberd server misconfiguration; `mod_private` was not enabled, and this is required by Movim. My thanks to @edhelas in helping to pin down the problem.
