### ISSUE TITLE
Movim fails to connect to ‎jabbercat@conference.zombofant.net

### ISSUE THREAD

**Issue by dos1** [movim/movim#686]
```
[16-Aug-2018 03:39:34 UTC] PHP Fatal error:  Uncaught PDOException: SQLSTATE[HY000]: General error: 1366 Incorrect string value: '\xF0\x9F\x98\xBA' for column 'description' at row 1 in /mnt/volume-fra1-01/www/movim/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:105
Stack trace:
#0 /mnt/volume-fra1-01/www/movim/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php(105): PDOStatement->execute(NULL)
#1 /mnt/volume-fra1-01/www/movim/vendor/illuminate/database/Connection.php(458): Doctrine\DBAL\Driver\PDOStatement->execute()
#2 /mnt/volume-fra1-01/www/movim/vendor/illuminate/database/Connection.php(657): Illuminate\Database\Connection->Illuminate\Database\{closure}('insert into `in...', Array)
#3 /mnt/volume-fra1-01/www/movim/vendor/illuminate/database/Connection.php(624): Illuminate\Database\Connection->runQueryCallback('insert into `in...', Array, Object(Closure))
#4 /mnt/volume-fra1-01/www/movim/vendor/illuminate/database/Connection.php(459): Illuminate\Database\Connection->run('insert into `in...', Array, Object(Closure))
#5 /mnt in /mnt/volume-fra1-01/www/movim/vendor/illuminate/database/Connection.php on line 664
```
On git from master.

**Comment by dos1** [comment]
```
mysql> SELECT * FROM INFORMATION_SCHEMA.SCHEMATA where schema_name="movim";
+--------------+-------------+----------------------------+------------------------+----------+
| CATALOG_NAME | SCHEMA_NAME | DEFAULT_CHARACTER_SET_NAME | DEFAULT_COLLATION_NAME | SQL_PATH |
+--------------+-------------+----------------------------+------------------------+----------+
| def          | movim       | utf8mb4                    | utf8mb4_polish_ci      | NULL     |
+--------------+-------------+----------------------------+------------------------+----------+
```
```
mysql> show variables like "%character%"; show variables like "%collation%";
+--------------------------+----------------------------+
| Variable_name            | Value                      |
+--------------------------+----------------------------+
| character_set_client     | utf8mb4                    |
| character_set_connection | utf8mb4                    |
| character_set_database   | utf8mb4                    |
| character_set_filesystem | binary                     |
| character_set_results    | utf8mb4                    |
| character_set_server     | utf8mb4                    |
| character_set_system     | utf8                       |
| character_sets_dir       | /usr/share/mysql/charsets/ |
+--------------------------+----------------------------+
8 rows in set (0.00 sec)

+----------------------+--------------------+
| Variable_name        | Value              |
+----------------------+--------------------+
| collation_connection | utf8mb4_general_ci |
| collation_database   | utf8mb4_polish_ci  |
| collation_server     | utf8mb4_polish_ci  |
+----------------------+--------------------+
```

**Comment by dos1** [comment]
FWIW, it works with SQLite database; didn't work with MySQL.

**Comment by dos1** [comment]
This conference room is problematic for other reasons as well: after connecting, I get two phantom unread messages in the counter that cannot be cleared in any way aside of logging out and back in :D

**Comment by edhelas** [comment]
Any news on that ticket?

**Comment by edhelas** [comment]
I just tried again and didn't got much more issues with this chatroom :) Closing.

**Comment by dos1** [comment]
It worked for me ever since I switched to SQLite and those two unread messages aren't appearing anymore too - probably simply got phased out of room's recent history :P
