### ISSUE TITLE
Crash when posting with tags

### ISSUE THREAD

**Issue by Natureshadow** [movim/movim#714]
```
[11-Sep-2018 16:47:40 UTC] PHP Fatal error:  Uncaught PDOException: SQLSTATE[23505]: Unique violation: 7 ERROR:  duplicate key value violates uniq
DETAIL:  Key (name)=(908595) already exists. in /var/www/movim/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:105
Stack trace:
#0 /var/www/movim/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php(105): PDOStatement->execute(NULL)
#1 /var/www/movim/vendor/illuminate/database/Connection.php(330): Doctrine\DBAL\Driver\PDOStatement->execute()
#2 /var/www/movim/vendor/illuminate/database/Connection.php(657): Illuminate\Database\Connection->Illuminate\Database\{closure}('insert into "ta..
#3 /var/www/movim/vendor/illuminate/database/Connection.php(624): Illuminate\Database\Connection->runQueryCallback('insert into "ta...', Array, Ob
#4 /var/www/movim/vendor/illuminate/database/Connection.php(333): Illuminate\Database\Connection->run('insert into "ta...', Array, Object(Closure)
#5 /var/www/movim/vendor/illuminate/database/Connection in /var/www/movim/vendor/illuminate/database/Connection.php on line 664
```

**Comment by Natureshadow** [comment]
This results in comments being disabled on the post.

Here is the relevant post:

https://commu.teckids.org/movim/?post/nik%40mercurius.teckids.org/urn%3Axmpp%3Amicroblog%3A0/908595-krb5-subdomain-and-ms-subdomain-update-policy-rules-ineffective-omvMXF
