### ISSUE TITLE
Database error on new install of 0.14.1rc

### ISSUE THREAD

**Issue by Natureshadow** [movim/movim#750]
On a newly installed instance with version 0.14.1rc, I get the following on login:

```
[17-Dec-2018 00:12:43 UTC] PHP Fatal error:  Uncaught PDOException: SQLSTATE[23503]: Foreign key violation: 7 ERROR:  insert or update on table "rosters" violates foreign key constraint "rosters_session_id_foreign"
DETAIL:  Key (session_id)=(WByeXz9KwtiQx9fa9K2MYEiDpMfXJRBI) is not present in table "sessions". in /usr/share/php/Doctrine/DBAL/Driver/PDOStatement.php:142
Stack trace:
#0 /usr/share/php/Doctrine/DBAL/Driver/PDOStatement.php(142): PDOStatement->execute(NULL)
#1 /usr/share/php/Illuminate/Database/Connection.php(458): Doctrine\DBAL\Driver\PDOStatement->execute()
#2 /usr/share/php/Illuminate/Database/Connection.php(657): Illuminate\Database\Connection->Illuminate\Database\{closure}('insert into "ro...', Array)
#3 /usr/share/php/Illuminate/Database/Connection.php(624): Illuminate\Database\Connection->runQueryCallback('insert into "ro...', Array, Object(Closure))
#4 /usr/share/php/Illuminate/Database/Connection.php(459): Illuminate\Database\Connection->run('insert into "ro...', Array, Object(Closure))
#5 /usr/share/php/Illuminate/Database/Connect in /usr/share/php/Illuminate/Database/Connection.php on line 664
```

This does not happen if the database was upgraded (migrated) from 0.14.

**Comment by edhelas** [comment]
So if I understand, this is happening on a fresh new database? But not a migrated one?

**Comment by Natureshadow** [comment]
Yes, somehow. I actually only got it working if the session was already in the DB before upgrading, but I cannot reproduce that on another instance.

Maybe we should just look into that next week in Leipzig together ☺.

**Comment by edhelas** [comment]
Is this still happening ?

**Comment by edhelas** [comment]
Closing the issue :)
