### ISSUE TITLE
PDOException: SQLSTATE[HY000]: General error: 1025 Error on rename

### ISSUE THREAD

**Issue by ghost** [movim/movim#844]
Can not install with mysql 5.7, Ubuntu 18.04, php 7.2. Here is the log.

```
PDOException: SQLSTATE[HY000]: General error: 1025 Error on rename of './movim_production/#sql-7514_1c8' to './movim_production/messages' (errno: 150 - Foreign key constraint is incorrectly formed) in /xxx/xxx/movim/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:105
Stack trace:
#0 /xxx/xxx/movim/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php(105): PDOStatement->execute(NULL)
#1 /xxx/xxx/movim/vendor/illuminate/database/Connection.php(458): Doctrine\DBAL\Driver\PDOStatement->execute()
#2 /xxx/xxx/movim/vendor/illuminate/database/Connection.php(657): Illuminate\Database\Connection->Illuminate\Database\{closure}('alter table `me...', Array)
#3 /xxx/xxx/movim/vendor/illuminate/database/Connection.php(624): Illuminate\Database\Connection->runQueryCallback('alter table `me...', Array, Object(Closure))
#4 /xxx/xxx/movim/vendor/illuminate/database/Connection.php(459): Illuminate\Database\Connection->run('alter table `me...', Array, Object(Closure))
#5 /xxx/xxx/movim/vendor/illuminate/database/Schema/Blueprint.php(86): Illuminate\Database\Connection->statement('alter table `me...')
#6 /xxx/xxx/movim/vendor/illuminate/database/Schema/Builder.php(252): Illuminate\Database\Schema\Blueprint->build(Object(Illuminate\Database\MySqlConnection), Object(Illuminate\Database\Schema\Grammars\MySqlGrammar))
#7 /xxx/xxx/movim/vendor/illuminate/database/Schema/Builder.php(149): Illuminate\Database\Schema\Builder->build(Object(Illuminate\Database\Schema\Blueprint))
#8 /xxx/xxx/movim/database/migrations/20190324190611_create_reactions_table.php(14): Illuminate\Database\Schema\Builder->table('messages', Object(Closure))
#9 /xxx/xxx/movim/vendor/robmorgan/phinx/src/Phinx/Migration/Manager/Environment.php(128): CreateReactionsTable->up()
#10 /xxx/xxx/movim/vendor/robmorgan/phinx/src/Phinx/Migration/Manager.php(387): Phinx\Migration\Manager\Environment->executeMigration(Object(CreateReactionsTable), 'up', false)
#11 /xxx/xxx/movim/vendor/robmorgan/phinx/src/Phinx/Migration/Manager.php(361): Phinx\Migration\Manager->executeMigration('movim', Object(CreateReactionsTable), 'up', false)
#12 /xxx/xxx/movim/vendor/robmorgan/phinx/src/Phinx/Console/Command/Migrate.php(122): Phinx\Migration\Manager->migrate('movim', 20190514162951, false)
#13 /xxx/xxx/movim/vendor/symfony/console/Command/Command.php(264): Phinx\Console\Command\Migrate->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 /xxx/xxx/movim/vendor/symfony/console/Application.php(874): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#15 /xxx/xxx/movim/vendor/symfony/console/Application.php(228): Symfony\Component\Console\Application->doRunCommand(Object(Phinx\Console\Command\Migrate), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#16 /xxx/xxx/movim/vendor/robmorgan/phinx/src/Phinx/Console/PhinxApplication.php(88): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#17 /xxx/xxx/movim/vendor/symfony/console/Application.php(130): Phinx\Console\PhinxApplication->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#18 /xxx/xxx/movim/vendor/robmorgan/phinx/bin/phinx(28): Symfony\Component\Console\Application->run()
#19 {main}

Next Doctrine\DBAL\Driver\PDOException: SQLSTATE[HY000]: General error: 1025 Error on rename of './movim_production/#sql-7514_1c8' to './movim_production/messages' (errno: 150 - Foreign key constraint is incorrectly formed) in /xxx/xxx/movim/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:107
Stack trace:
#0 /xxx/xxx/movim/vendor/illuminate/database/Connection.php(458): Doctrine\DBAL\Driver\PDOStatement->execute()
#1 /xxx/xxx/movim/vendor/illuminate/database/Connection.php(657): Illuminate\Database\Connection->Illuminate\Database\{closure}('alter table `me...', Array)
#2 /xxx/xxx/movim/vendor/illuminate/database/Connection.php(624): Illuminate\Database\Connection->runQueryCallback('alter table `me...', Array, Object(Closure))
#3 /xxx/xxx/movim/vendor/illuminate/database/Connection.php(459): Illuminate\Database\Connection->run('alter table `me...', Array, Object(Closure))
#4 /xxx/xxx/movim/vendor/illuminate/database/Schema/Blueprint.php(86): Illuminate\Database\Connection->statement('alter table `me...')
#5 /xxx/xxx/movim/vendor/illuminate/database/Schema/Builder.php(252): Illuminate\Database\Schema\Blueprint->build(Object(Illuminate\Database\MySqlConnection), Object(Illuminate\Database\Schema\Grammars\MySqlGrammar))
#6 /xxx/xxx/movim/vendor/illuminate/database/Schema/Builder.php(149): Illuminate\Database\Schema\Builder->build(Object(Illuminate\Database\Schema\Blueprint))
#7 /xxx/xxx/movim/database/migrations/20190324190611_create_reactions_table.php(14): Illuminate\Database\Schema\Builder->table('messages', Object(Closure))
#8 /xxx/xxx/movim/vendor/robmorgan/phinx/src/Phinx/Migration/Manager/Environment.php(128): CreateReactionsTable->up()
#9 /xxx/xxx/movim/vendor/robmorgan/phinx/src/Phinx/Migration/Manager.php(387): Phinx\Migration\Manager\Environment->executeMigration(Object(CreateReactionsTable), 'up', false)
#10 /xxx/xxx/movim/vendor/robmorgan/phinx/src/Phinx/Migration/Manager.php(361): Phinx\Migration\Manager->executeMigration('movim', Object(CreateReactionsTable), 'up', false)
#11 /xxx/xxx/movim/vendor/robmorgan/phinx/src/Phinx/Console/Command/Migrate.php(122): Phinx\Migration\Manager->migrate('movim', 20190514162951, false)
#12 /xxx/xxx/movim/vendor/symfony/console/Command/Command.php(264): Phinx\Console\Command\Migrate->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 /xxx/xxx/movim/vendor/symfony/console/Application.php(874): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 /xxx/xxx/movim/vendor/symfony/console/Application.php(228): Symfony\Component\Console\Application->doRunCommand(Object(Phinx\Console\Command\Migrate), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#15 /xxx/xxx/movim/vendor/robmorgan/phinx/src/Phinx/Console/PhinxApplication.php(88): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#16 /xxx/xxx/movim/vendor/symfony/console/Application.php(130): Phinx\Console\PhinxApplication->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#17 /xxx/xxx/movim/vendor/robmorgan/phinx/bin/phinx(28): Symfony\Component\Console\Application->run()
#18 {main}

Next Illuminate\Database\QueryException: SQLSTATE[HY000]: General error: 1025 Error on rename of './movim_production/#sql-7514_1c8' to './movim_production/messages' (errno: 150 - Foreign key constraint is incorrectly formed) (SQL: alter table `messages` drop primary key) in /xxx/xxx/movim/vendor/illuminate/database/Connection.php:664
Stack trace:
#0 /xxx/xxx/movim/vendor/illuminate/database/Connection.php(624): Illuminate\Database\Connection->runQueryCallback('alter table `me...', Array, Object(Closure))
#1 /xxx/xxx/movim/vendor/illuminate/database/Connection.php(459): Illuminate\Database\Connection->run('alter table `me...', Array, Object(Closure))
#2 /xxx/xxx/movim/vendor/illuminate/database/Schema/Blueprint.php(86): Illuminate\Database\Connection->statement('alter table `me...')
#3 /xxx/xxx/movim/vendor/illuminate/database/Schema/Builder.php(252): Illuminate\Database\Schema\Blueprint->build(Object(Illuminate\Database\MySqlConnection), Object(Illuminate\Database\Schema\Grammars\MySqlGrammar))
#4 /xxx/xxx/movim/vendor/illuminate/database/Schema/Builder.php(149): Illuminate\Database\Schema\Builder->build(Object(Illuminate\Database\Schema\Blueprint))
#5 /xxx/xxx/movim/database/migrations/20190324190611_create_reactions_table.php(14): Illuminate\Database\Schema\Builder->table('messages', Object(Closure))
#6 /xxx/xxx/movim/vendor/robmorgan/phinx/src/Phinx/Migration/Manager/Environment.php(128): CreateReactionsTable->up()
#7 /xxx/xxx/movim/vendor/robmorgan/phinx/src/Phinx/Migration/Manager.php(387): Phinx\Migration\Manager\Environment->executeMigration(Object(CreateReactionsTable), 'up', false)
#8 /xxx/xxx/movim/vendor/robmorgan/phinx/src/Phinx/Migration/Manager.php(361): Phinx\Migration\Manager->executeMigration('movim', Object(CreateReactionsTable), 'up', false)
#9 /xxx/xxx/movim/vendor/robmorgan/phinx/src/Phinx/Console/Command/Migrate.php(122): Phinx\Migration\Manager->migrate('movim', 20190514162951, false)
#10 /xxx/xxx/movim/vendor/symfony/console/Command/Command.php(264): Phinx\Console\Command\Migrate->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 /xxx/xxx/movim/vendor/symfony/console/Application.php(874): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 /xxx/xxx/movim/vendor/symfony/console/Application.php(228): Symfony\Component\Console\Application->doRunCommand(Object(Phinx\Console\Command\Migrate), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 /xxx/xxx/movim/vendor/robmorgan/phinx/src/Phinx/Console/PhinxApplication.php(88): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 /xxx/xxx/movim/vendor/symfony/console/Application.php(130): Phinx\Console\PhinxApplication->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#15 /xxx/xxx/movim/vendor/robmorgan/phinx/bin/phinx(28): Symfony\Component\Console\Application->run()
#16 {main}
```

**Comment by edhelas** [comment]
Did you tried to migrate from a non utf8-mb4 MySQL DB ?
I'd suggest to start from a blank DB, don't worry, the SQL DB is mostly cache from the XMPP network.
I'd also strongly advise to move to PostgreSQL if you can :)
