### ISSUE TITLE
Database migrations failed on 54bd3b1a518f1a0931073963c27cbfc823217972

### ISSUE THREAD

**Issue by pztrn** [movim/movim#869]
```
% php ./composer.phar movim:migrate
> vendor/bin/phinx migrate --ansi
PHP Fatal error:  Uncaught Symfony\Component\Console\Exception\LogicException: The command defined in "Phinx\Console\Command\Init" cannot have an empty name. in /home/movim/movim/vendor/symfony/console/Command/Command.php:453
Stack trace:
#0 /home/movim/movim/vendor/robmorgan/phinx/src/Phinx/Console/Command/Init.php(47): Symfony\Component\Console\Command\Command->getName()
#1 /home/movim/movim/vendor/symfony/console/Command/Command.php(77): Phinx\Console\Command\Init->configure()
#2 /home/movim/movim/vendor/robmorgan/phinx/src/Phinx/Console/PhinxApplication.php(60): Symfony\Component\Console\Command\Command->__construct()
#3 /home/movim/movim/vendor/robmorgan/phinx/app/phinx.php(36): Phinx\Console\PhinxApplication->__construct()
#4 /home/movim/movim/vendor/robmorgan/phinx/bin/phinx(27): require('/home/movim/mov...')
#5 {main}
  thrown in /home/movim/movim/vendor/symfony/console/Command/Command.php on line 453
Script vendor/bin/phinx migrate --ansi handling the movim:migrate event returned with error code 255
```

Done git pull && composer install. On rev 54bd3b1a518f1a0931073963c27cbfc823217972. Debian 10, php 7.3.4, PostgreSQL 11.2.

**Comment by edhelas** [comment]
Fixed there https://github.com/movim/movim/commit/ed7e0fe573d6bfdc89b351ed50159e1b2f1368a8
