### ISSUE TITLE
error when trying to populate database

### ISSUE THREAD

**Issue by raspbeguy** [movim/movim#871]
Hello,

I'm trying to install Movim following the wiki https://github.com/movim/movim/wiki/Install-Movim using a stable release on Ubuntu 18.10.

I created the following database configuration:
```php
<?php
# This is the database configuration of Movim
# You need to copy an rename this file to 'db.inc.php' and complete the values
$conf = [
    # The type can be 'pgsql' or 'mysql'
    'type'        => 'mysql',
    # The database username
    'username'    => 'movim',
    # The password
    'password'    => '*********',
    # Where can we find the database ?
    'host'        => 'db.example.com',
    # The port number, 3306 for MySQL and 5432 for PostgreSQL
    'port'        => 3306,
    # The database name
    'database'    => 'movim'
];
```

When I get to the step `composer movim:migrate` I ha this error:
```
> vendor/bin/phinx migrate --ansi
PHP Fatal error:  Uncaught Symfony\Component\Console\Exception\LogicException: The command defined in "Phinx\Console\Command\Init" cannot have an empty name. in /srv/http/movim-0.15/vendor/symfony/console/Command/Command.php:453
Stack trace:
#0 /srv/http/movim-0.15/vendor/robmorgan/phinx/src/Phinx/Console/Command/Init.php(47): Symfony\Component\Console\Command\Command->getName()
#1 /srv/http/movim-0.15/vendor/symfony/console/Command/Command.php(77): Phinx\Console\Command\Init->configure()
#2 /srv/http/movim-0.15/vendor/robmorgan/phinx/src/Phinx/Console/PhinxApplication.php(60): Symfony\Component\Console\Command\Command->__construct()
#3 /srv/http/movim-0.15/vendor/robmorgan/phinx/app/phinx.php(36): Phinx\Console\PhinxApplication->__construct()
#4 /srv/http/movim-0.15/vendor/robmorgan/phinx/bin/phinx(27): require('/srv/http/movim...')
#5 {main}
  thrown in /srv/http/movim-0.15/vendor/symfony/console/Command/Command.php on line 453
Script vendor/bin/phinx migrate --ansi handling the movim:migrate event returned with error code 255
```

I tried the same on a Debian 10, same result.

**Comment by yabb85** [comment]
This error is fixed with release un master branch.
I have also this error with 0.15.

**Comment by edhelas** [comment]
I'm closing this ticket, it was fixed in master and a stable release should arrive anytime soon.
