### ISSUE TITLE
Error when I try to create the database structure with phinx

### ISSUE THREAD

**Issue by Vertux** [movim/movim#885]
Fresh installation of Movim v0.16 with postgresql database

When I execute the command:

> Once the database is setup create the database structure using Phinx.

`php composer.phar movim:migrate`

I get the following error:

```
php composer.phar movim:migrate
> vendor/bin/phinx migrate --ansi
Phinx by CakePHP - https://phinx.org. 0.11.1

using config file ./phinx.php
An error occured, check syslog for more information
An error occured, check syslog for more information
An error occured, check syslog for more information
PHP Fatal error:  Uncaught Error: Class 'Utils' not found in /var/www/vhosts/xxx/xxx/movim/src/Movim/Bootstrap.php:302
Stack trace:
#0 /var/www/vhosts/xxx/xxx/movim/src/Movim/Bootstrap.php(313): Movim\Bootstrap->systemErrorHandler(1, 'Error: Class 'U...', '/var/www/vhosts...', 302, '#0 [internal fu...')
#1 [internal function]: Movim\Bootstrap->exceptionHandler(Object(Error))
#2 {main}
  thrown in /var/www/vhosts/xxx/xxx/movim/src/Movim/Bootstrap.php on line 302
PHP Fatal error:  Uncaught Error: Class 'Utils' not found in /var/www/vhosts/xxx/xxx/movim/src/Movim/Bootstrap.php:302
Stack trace:
#0 /var/www/vhosts/xxx/xxx/movim/src/Movim/Bootstrap.php(325): Movim\Bootstrap->systemErrorHandler(1, 'Uncaught Error:...', '/var/www/vhosts...', 302)
#1 [internal function]: Movim\Bootstrap->fatalErrorShutdownHandler()
#2 {main}
  thrown in /var/www/vhosts/xxx/xxx/movim/src/Movim/Bootstrap.php on line 302
Script vendor/bin/phinx migrate --ansi handling the movim:migrate event returned with error code 255
```

**Comment by Vertux** [comment]
It is weird, i did another installation attempt and now it worked. The only thing I have changed was the database name **from movim_production** to **movim**. 
Maybe I have done a mistake when I have tried it the first time and overlooked it.

Edit: Is the PHP notice `Constant SQL_DATE already defined` normal?
```
> vendor/bin/phinx migrate --ansi
Phinx by CakePHP - https://phinx.org. 0.11.1

using config file ./phinx.php
PHP Notice:  Constant SQL_DATE already defined in /var/www/vhosts/xxxx/xxxx/src/Movim/Bootstrap.php on line 110
using config parser php
using migration paths
 - /var/www/vhosts/xxxx/xxxx/database/migrations
using seed paths
 - /var/www/vhosts/xxxx/xxxx/database/seeds
warning no environment specified, defaulting to: movim
using adapter pgsql
using database movim
```
