### ISSUE TITLE
duplicate key value violates unique constraint "conferences_pkey"

### ISSUE THREAD

**Issue by Ppjet6** [movim/movim#887]
Movim version: a63342e1f
php version: 7.4

# Steps to reproduce

- Add bookmark
- ???

# What happens

```
movim.ERROR: Illuminate\Database\QueryException: SQLSTATE[23505]: Unique violation: 7 ERROR:  duplicate key value violates unique constraint "conferences_pkey" DETAIL:  Key (session_id, conference)=(QWvWceBbGwhAULR0RCqV000nAVXjS2Il, mov
im@conference.movim.eu) already exists. (SQL: insert into "conferences" ("session_id", "conference", "name", "autojoin", "nick", "updated_at", "created_at") values (QWvWceBbGwhAULR0RCqV000nAVXjS2Il, movim@conference.movim.eu, Foo, 0, pep_, 2019-12-04 18:42:16, 2019-12-04 1
8:42:16)) in /usr/share/webapps/movim/vendor/illuminate/database/Connection.php (line 664) Trace #0 /usr/share/webapps/movim/vendor/illuminate/database/Connection.php(624): Illuminate\Database\Connection->runQueryCallback('insert into "co...', Array, Object(Closure)) #1 /u
sr/share/webapps/movim/vendor/illuminate/database/Connection.php(459): Illuminate\Database\Connection->run('insert into "co...', Array, Object(Closure)) #2 /usr/share/webapps/movim/vendor/illuminate/database/Connection.php(411): Illuminate\Database\Connection->statement('i
nsert into "co...', Array) #3 /usr/share/webapps/movim/vendor/illuminate/database/Query/Builder.php(2646): Illuminate\Database\Connection->insert('insert into "co...', Array) #4 /usr/share/webapps/movim/vendor/illuminate/database/Eloquent/Builder.php(1353): Illuminate\Data
base\Query\Builder->insert(Array) #5 /usr/share/webapps/movim/vendor/illuminate/database/Eloquent/Model.php(815): Illuminate\Database\Eloquent\Builder->__call('insert', Array) #6 /usr/share/webapps/movim/vendor/illuminate/database/Eloquent/Model.php(667): Illuminate\Databa
se\Eloquent\Model->performInsert(Object(Illuminate\Database\Eloquent\Builder)) #7 /usr/share/webapps/movim/src/Movim/Model.php(50): Illuminate\Database\Eloquent\Model->save(Array) #8 /usr/share/webapps/movim/lib/moxl/src/Moxl/Xec/Action/Bookmark2/Set.php(27): Movim\Model->
save() #9 /usr/share/webapps/movim/lib/moxl/src/Moxl/Xec/Handler.php(61): Moxl\Xec\Action\Bookmark2\Set->handle(Object(SimpleXMLElement)) #10 /usr/share/webapps/movim/linker.php(33): Moxl\Xec\Handler::handle(Object(SimpleXMLElement)) #11 [internal function]: {closure}(Obje
ct(SimpleXMLElement)) #12 /usr/share/webapps/movim/lib/moxl/src/Moxl/Parser.php(104): call_user_func_array(Object(Closure), Array) #13 [internal function]: Moxl\Parser->end(Resource id #377, 'iq') #14 /usr/share/webapps/movim/lib/moxl/src/Moxl/Parser.php(49): xml_parse(Res
ource id #377, '<message id='oM...', false) #15 /usr/share/webapps/movim/linker.php(252): Moxl\Parser->parse('<message id='oM...') #16 /usr/share/webapps/movim/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(123): {closure}('<message id='oM...') #17 /usr/sha
re/webapps/movim/vendor/react/stream/src/Util.php(71): Evenement\EventEmitter->emit('data', Array) #18 /usr/share/webapps/movim/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(123): React\Stream\Util::React\Stream\{closure}('<message id='oM...') #19 /usr/sha
re/webapps/movim/vendor/react/stream/src/DuplexResourceStream.php(193): Evenement\EventEmitter->emit('data', Array) #20 /usr/share/webapps/movim/vendor/react/event-loop/src/StreamSelectLoop.php(244): React\Stream\DuplexResourceStream->handleData(Resource id #300) #21 /usr/
share/webapps/movim/vendor/react/event-loop/src/StreamSelectLoop.php(211): React\EventLoop\StreamSelectLoop->waitForStreamActivity(4912328) #22 /usr/share/webapps/movim/linker.php(282): React\EventLoop\StreamSelectLoop->run() #23 {main} [] []
```

This is a test account, no room was being displayed when I first logged in. It might be possible that this room has been added as a bookmark to the account some time in the past, and it's been a while I haven't logged in with it on any movim instance.

**Comment by Vertux** [comment]
I can confirm this issue.

**My environment (Ubuntu v18.0.4):**

Movim: v0.16.2
PHP v7.4.1
postgresql: v10.10

I get this error. I cannot tell you which action has triggerd the error.

```
Dez 21 21:26:19 movim movim[22186]: movim.ERROR: Illuminate\Database\QueryException: SQLSTATE[23505]: Unique violation: 7 ERROR:  duplicate key value violates unique constraint "conferences_pkey" DETAIL:  Key (session_id
Dez 21 21:26:39 movim movim[22186]: movim.ERROR: Illuminate\Database\QueryException: SQLSTATE[23505]: Unique violation: 7 ERROR:  duplicate key value violates unique constraint "conferences_pkey" DETAIL:  Key (session_id
Dez 21 21:31:45 movim movim[22186]: movim.ERROR: Illuminate\Database\QueryException: SQLSTATE[23505]: Unique violation: 7 ERROR:  duplicate key value violates unique constraint "conferences_pkey" DETAIL:  Key (session_id
```

**Comment by edhelas** [comment]
I can't reproduce the issue
