### ISSUE TITLE
Get disconnected with the daemon when I try to connect to Movim

### ISSUE THREAD

**Issue by rdelaage** [movim/movim#951]
Hi,
I wanted to try Movim today so I followed the installation wiki. Everything was going well , in the admin dashboard everything was marked as good, but when I try to connect to movim with my XMPP account, the daemon suddenly get disconnected, I tried to search what was going wrong using --debug and --verbose but I've seen nothing wrong.
The only strange thing I've seen is that an error appears in the web browser developer's console "BASE_URI is not defined".
My configuration is an Nginx server with a postresql server. I've paste the config given by deamon.php in movim.conf.
Thank you for your work.

**Comment by rdelaage** [comment]
It seems this issue is resolved when I replace ' + BASE_URI + ' in the file public/scripts/movim_websocket.js, it was on version v0.18.
Yet I still having issues and in log/errors.log there are these lines :
```
movim.ERROR: Declaration of Movim\Model::setKeysForSaveQuery(Illuminate\Database\Eloquent\Builder $query) should be compatible with Illuminate\Database\Eloquent\Model::setKeysForSaveQuery($query) in /BACKUP/movim/src/Movim/Model.php (line 0) Trace  [] []
movim.ERROR: Declaration of Movim\Model::setKeysForSaveQuery(Illuminate\Database\Eloquent\Builder $query) should be compatible with Illuminate\Database\Eloquent\Model::setKeysForSaveQuery($query) in /BACKUP/movim/src/Movim/Model.php (line 104) Trace  [] []
movim.ERROR: stream_socket_client(): unable to connect to tcp://[2a00:99a0:0:1000::7]:5222 (Network is unreachable) in /BACKUP/movim/vendor/react/socket/src/TcpConnector.php (line 82) Trace  [] []
movim.ERROR: TypeError: Return value of "Movim\Console\ConfigCommand::execute()" must be of the type int, "null" returned. in /BACKUP/movim/vendor/symfony/console/Command/Command.php (line 258) Trace #0 /BACKUP/movim/vendor/symfony/console/Application.php(971): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #1 /BACKUP/movim/vendor/symfony/console/Application.php(290): Symfony\Component\Console\Application->doRunCommand(Object(Movim\Console\ConfigCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #2 /BACKUP/movim/vendor/symfony/console/Application.php(166): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #3 /BACKUP/movim/daemon.php(20): Symfony\Component\Console\Application->run() #4 {main} [] []
```

**Comment by edhelas** [comment]
Which version? Did you tried master ?

**Comment by rdelaage** [comment]
I didn't ! Thank you it works :)
