### ISSUE TITLE
Problem running migrations of first install on MySQL

### ISSUE THREAD

**Issue by fabiomontefuscolo** [movim/movim#998]
I tried to follow the documentation, but I got some errors during the installation process

* OS: Ubuntu 20.04.1 LTS (Focal Fossa)
* MySQL:  8.0.22-0ubuntu0.20.04.3 (Ubuntu)
* Composer: Composer version 2.0.8 2020-12-03 17:20:38
* PHP: 7.4.13, Zend Engine v3.4.0, OPcache v7.4.13

## First error
```
Next Illuminate\Database\QueryException: SQLSTATE[42000]: Syntax error or access violation: 1170 BLOB/TEXT column 'url' used in key specification without a key length (SQL: alter table `embeds` add unique `embeds_draft_id_url_unique`(`draft_id`, `url`)) in /home/montefuscolo/domains/movim.montefuscolo.com.br/movim/vendor/illuminate/database/Connection.php:685
Stack trace:
#0 /home/montefuscolo/domains/movim.montefuscolo.com.br/movim/vendor/illuminate/database/Connection.php(645): Illuminate\Database\Connection->runQueryCallback()
#1 /home/montefuscolo/domains/movim.montefuscolo.com.br/movim/vendor/illuminate/database/Connection.php(479): Illuminate\Database\Connection->run()
#2 /home/montefuscolo/domains/movim.montefuscolo.com.br/movim/vendor/illuminate/database/Schema/Blueprint.php(109): Illuminate\Database\Connection->statement()
#3 /home/montefuscolo/domains/movim.montefuscolo.com.br/movim/vendor/illuminate/database/Schema/Builder.php(365): Illuminate\Database\Schema\Blueprint->build()
#4 /home/montefuscolo/domains/movim.montefuscolo.com.br/movim/vendor/illuminate/database/Schema/Builder.php(228): Illuminate\Database\Schema\Builder->build()
#5 /home/montefuscolo/domains/movim.montefuscolo.com.br/movim/database/migrations/20210329190212_create_drafts_table.php(47): Illuminate\Database\Schema\Builder->create()
#6 /home/montefuscolo/domains/movim.montefuscolo.com.br/movim/vendor/robmorgan/phinx/src/Phinx/Migration/Manager/Environment.php(112): CreateDraftsTable->up()
#7 /home/montefuscolo/domains/movim.montefuscolo.com.br/movim/vendor/robmorgan/phinx/src/Phinx/Migration/Manager.php(382): Phinx\Migration\Manager\Environment->executeMigration()
#8 /home/montefuscolo/domains/movim.montefuscolo.com.br/movim/vendor/robmorgan/phinx/src/Phinx/Migration/Manager.php(356): Phinx\Migration\Manager->executeMigration()
#9 /home/montefuscolo/domains/movim.montefuscolo.com.br/movim/vendor/robmorgan/phinx/src/Phinx/Console/Command/Migrate.php(123): Phinx\Migration\Manager->migrate()
#10 /home/montefuscolo/domains/movim.montefuscolo.com.br/movim/vendor/symfony/console/Command/Command.php(288): Phinx\Console\Command\Migrate->execute()
#11 /home/montefuscolo/domains/movim.montefuscolo.com.br/movim/vendor/symfony/console/Application.php(974): Symfony\Component\Console\Command\Command->run()
#12 /home/montefuscolo/domains/movim.montefuscolo.com.br/movim/vendor/symfony/console/Application.php(291): Symfony\Component\Console\Application->doRunCommand()
#13 /home/montefuscolo/domains/movim.montefuscolo.com.br/movim/vendor/robmorgan/phinx/src/Phinx/Console/PhinxApplication.php(69): Symfony\Component\Console\Application->doRun()
#14 /home/montefuscolo/domains/movim.montefuscolo.com.br/movim/vendor/symfony/console/Application.php(167): Phinx\Console\PhinxApplication->doRun()
#15 /home/montefuscolo/domains/movim.montefuscolo.com.br/movim/vendor/robmorgan/phinx/bin/phinx(28): Symfony\Component\Console\Application->run()
#16 {main}
Script vendor/bin/phinx migrate --ansi handling the movim:migrate event returned with error code 1
```

## Second error
```
Next Illuminate\Database\QueryException: SQLSTATE[42000]: Syntax error or access violation: 1067 Invalid default value for 'admin' (SQL: alter table `users` add `admin` tinyint(1) not null default 'false') in /home/montefuscolo/domains/movim.montefuscolo.com.br/movim/vendor/illuminate/database/Connection.php:685
Stack trace:
#0 /home/montefuscolo/domains/movim.montefuscolo.com.br/movim/vendor/illuminate/database/Connection.php(645): Illuminate\Database\Connection->runQueryCallback()
#1 /home/montefuscolo/domains/movim.montefuscolo.com.br/movim/vendor/illuminate/database/Connection.php(479): Illuminate\Database\Connection->run()
#2 /home/montefuscolo/domains/movim.montefuscolo.com.br/movim/vendor/illuminate/database/Schema/Blueprint.php(109): Illuminate\Database\Connection->statement()
#3 /home/montefuscolo/domains/movim.montefuscolo.com.br/movim/vendor/illuminate/database/Schema/Builder.php(365): Illuminate\Database\Schema\Blueprint->build()
#4 /home/montefuscolo/domains/movim.montefuscolo.com.br/movim/vendor/illuminate/database/Schema/Builder.php(212): Illuminate\Database\Schema\Builder->build()
#5 /home/montefuscolo/domains/movim.montefuscolo.com.br/movim/database/migrations/20210510204138_add_admin_column_to_users_table.php(13): Illuminate\Database\Schema\Builder->table()
#6 /home/montefuscolo/domains/movim.montefuscolo.com.br/movim/vendor/robmorgan/phinx/src/Phinx/Migration/Manager/Environment.php(112): AddAdminColumnToUsersTable->up()
#7 /home/montefuscolo/domains/movim.montefuscolo.com.br/movim/vendor/robmorgan/phinx/src/Phinx/Migration/Manager.php(382): Phinx\Migration\Manager\Environment->executeMigration()
#8 /home/montefuscolo/domains/movim.montefuscolo.com.br/movim/vendor/robmorgan/phinx/src/Phinx/Migration/Manager.php(356): Phinx\Migration\Manager->executeMigration()
#9 /home/montefuscolo/domains/movim.montefuscolo.com.br/movim/vendor/robmorgan/phinx/src/Phinx/Console/Command/Migrate.php(123): Phinx\Migration\Manager->migrate()
#10 /home/montefuscolo/domains/movim.montefuscolo.com.br/movim/vendor/symfony/console/Command/Command.php(288): Phinx\Console\Command\Migrate->execute()
#11 /home/montefuscolo/domains/movim.montefuscolo.com.br/movim/vendor/symfony/console/Application.php(974): Symfony\Component\Console\Command\Command->run()
#12 /home/montefuscolo/domains/movim.montefuscolo.com.br/movim/vendor/symfony/console/Application.php(291): Symfony\Component\Console\Application->doRunCommand()
#13 /home/montefuscolo/domains/movim.montefuscolo.com.br/movim/vendor/robmorgan/phinx/src/Phinx/Console/PhinxApplication.php(69): Symfony\Component\Console\Application->doRun()
#14 /home/montefuscolo/domains/movim.montefuscolo.com.br/movim/vendor/symfony/console/Application.php(167): Phinx\Console\PhinxApplication->doRun()
#15 /home/montefuscolo/domains/movim.montefuscolo.com.br/movim/vendor/robmorgan/phinx/bin/phinx(28): Symfony\Component\Console\Application->run()
#16 {main}
Script vendor/bin/phinx migrate --ansi handling the movim:migrate event returned with error code 1
```

**Comment by eugenshe** [comment]
Hi! I had the same problem with MySQL 5.7
the reason is https://stackoverflow.com/a/1827099

I've fixed it by switching to PostgreSQL :)

**Comment by edhelas** [comment]
Damn MySQL …

**Comment by xundeenergie** [comment]
I have the same with mariadb 10.3. Dont want to switch to postgresl, because i've running already a mariadb-service on that server... please fix it.

**Comment by edhelas** [comment]
I'll try to fix it asap

**Comment by xundeenergie** [comment]
Thank you :)
